version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        logger:
          deny:
            - pkg: github.com/sirupsen/logrus
    dupl:
      threshold: 100
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - octalLiteral
        - sloppyReassign
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 300
    gocyclo:
      min-complexity: 15
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: UK
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - goconst
          - gosec
          - noctx
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/NethermindEth/aztec-p2p-explorer)
    goimports:
      local-prefixes:
        - github.com/NethermindEth/aztec-p2p-explorer
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
