// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AutonomousSystem is an object representing the database table.
type AutonomousSystem struct {
	// A unique id that identifies an autonomous system.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// The autonomous system number.
	AsNumber int `boil:"as_number" json:"as_number" toml:"as_number" yaml:"as_number"`
	// The autonomous system organisation name.
	AsName string `boil:"as_name" json:"as_name" toml:"as_name" yaml:"as_name"`

	R *autonomousSystemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L autonomousSystemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AutonomousSystemColumns = struct {
	ID       string
	AsNumber string
	AsName   string
}{
	ID:       "id",
	AsNumber: "as_number",
	AsName:   "as_name",
}

var AutonomousSystemTableColumns = struct {
	ID       string
	AsNumber string
	AsName   string
}{
	ID:       "autonomous_systems.id",
	AsNumber: "autonomous_systems.as_number",
	AsName:   "autonomous_systems.as_name",
}

// Generated where

var AutonomousSystemWhere = struct {
	ID       whereHelperint
	AsNumber whereHelperint
	AsName   whereHelperstring
}{
	ID:       whereHelperint{field: "\"autonomous_systems\".\"id\""},
	AsNumber: whereHelperint{field: "\"autonomous_systems\".\"as_number\""},
	AsName:   whereHelperstring{field: "\"autonomous_systems\".\"as_name\""},
}

// AutonomousSystemRels is where relationship names are stored.
var AutonomousSystemRels = struct {
	AsIPAddresses string
}{
	AsIPAddresses: "AsIPAddresses",
}

// autonomousSystemR is where relationships are stored.
type autonomousSystemR struct {
	AsIPAddresses IPAddressSlice `boil:"AsIPAddresses" json:"AsIPAddresses" toml:"AsIPAddresses" yaml:"AsIPAddresses"`
}

// NewStruct creates a new relationship struct
func (*autonomousSystemR) NewStruct() *autonomousSystemR {
	return &autonomousSystemR{}
}

func (o *AutonomousSystem) GetAsIPAddresses() IPAddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetAsIPAddresses()
}

func (r *autonomousSystemR) GetAsIPAddresses() IPAddressSlice {
	if r == nil {
		return nil
	}

	return r.AsIPAddresses
}

// autonomousSystemL is where Load methods for each relationship are stored.
type autonomousSystemL struct{}

var (
	autonomousSystemAllColumns            = []string{"id", "as_number", "as_name"}
	autonomousSystemColumnsWithoutDefault = []string{"as_number", "as_name"}
	autonomousSystemColumnsWithDefault    = []string{"id"}
	autonomousSystemPrimaryKeyColumns     = []string{"id"}
	autonomousSystemGeneratedColumns      = []string{"id"}
)

type (
	// AutonomousSystemSlice is an alias for a slice of pointers to AutonomousSystem.
	// This should almost always be used instead of []AutonomousSystem.
	AutonomousSystemSlice []*AutonomousSystem

	autonomousSystemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	autonomousSystemType                 = reflect.TypeOf(&AutonomousSystem{})
	autonomousSystemMapping              = queries.MakeStructMapping(autonomousSystemType)
	autonomousSystemPrimaryKeyMapping, _ = queries.BindMapping(autonomousSystemType, autonomousSystemMapping, autonomousSystemPrimaryKeyColumns)
	autonomousSystemInsertCacheMut       sync.RWMutex
	autonomousSystemInsertCache          = make(map[string]insertCache)
	autonomousSystemUpdateCacheMut       sync.RWMutex
	autonomousSystemUpdateCache          = make(map[string]updateCache)
	autonomousSystemUpsertCacheMut       sync.RWMutex
	autonomousSystemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single autonomousSystem record from the query.
func (q autonomousSystemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AutonomousSystem, error) {
	o := &AutonomousSystem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for autonomous_systems")
	}

	return o, nil
}

// All returns all AutonomousSystem records from the query.
func (q autonomousSystemQuery) All(ctx context.Context, exec boil.ContextExecutor) (AutonomousSystemSlice, error) {
	var o []*AutonomousSystem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AutonomousSystem slice")
	}

	return o, nil
}

// Count returns the count of all AutonomousSystem records in the query.
func (q autonomousSystemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count autonomous_systems rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q autonomousSystemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if autonomous_systems exists")
	}

	return count > 0, nil
}

// AsIPAddresses retrieves all the ip_address's IPAddresses with an executor via as_id column.
func (o *AutonomousSystem) AsIPAddresses(mods ...qm.QueryMod) ipAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ip_addresses\".\"as_id\"=?", o.ID),
	)

	return IPAddresses(queryMods...)
}

// LoadAsIPAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (autonomousSystemL) LoadAsIPAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAutonomousSystem any, mods queries.Applicator) error {
	var slice []*AutonomousSystem
	var object *AutonomousSystem

	if singular {
		var ok bool
		object, ok = maybeAutonomousSystem.(*AutonomousSystem)
		if !ok {
			object = new(AutonomousSystem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAutonomousSystem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAutonomousSystem))
			}
		}
	} else {
		s, ok := maybeAutonomousSystem.(*[]*AutonomousSystem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAutonomousSystem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAutonomousSystem))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &autonomousSystemR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &autonomousSystemR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ip_addresses`),
		qm.WhereIn(`ip_addresses.as_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ip_addresses")
	}

	var resultSlice []*IPAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ip_addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on ip_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for ip_addresses")
	}

	if singular {
		object.R.AsIPAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &ipAddressR{}
			}
			foreign.R.As = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AsID) {
				local.R.AsIPAddresses = append(local.R.AsIPAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &ipAddressR{}
				}
				foreign.R.As = local
				break
			}
		}
	}

	return nil
}

// AddAsIPAddresses adds the given related objects to the existing relationships
// of the autonomous_system, optionally inserting them as new records.
// Appends related to o.R.AsIPAddresses.
// Sets related.R.As appropriately.
func (o *AutonomousSystem) AddAsIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AsID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ip_addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"as_id"}),
				strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AsID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &autonomousSystemR{
			AsIPAddresses: related,
		}
	} else {
		o.R.AsIPAddresses = append(o.R.AsIPAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &ipAddressR{
				As: o,
			}
		} else {
			rel.R.As = o
		}
	}
	return nil
}

// SetAsIPAddresses removes all previously related items of the
// autonomous_system replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.As's AsIPAddresses accordingly.
// Replaces o.R.AsIPAddresses with related.
// Sets related.R.As's AsIPAddresses accordingly.
func (o *AutonomousSystem) SetAsIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	query := "update \"ip_addresses\" set \"as_id\" = null where \"as_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.AsIPAddresses {
			queries.SetScanner(&rel.AsID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.As = nil
		}
		o.R.AsIPAddresses = nil
	}

	return o.AddAsIPAddresses(ctx, exec, insert, related...)
}

// RemoveAsIPAddresses relationships from objects passed in.
// Removes related items from R.AsIPAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.As.
func (o *AutonomousSystem) RemoveAsIPAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*IPAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AsID, nil)
		if rel.R != nil {
			rel.R.As = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("as_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.AsIPAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.AsIPAddresses)
			if ln > 1 && i < ln-1 {
				o.R.AsIPAddresses[i] = o.R.AsIPAddresses[ln-1]
			}
			o.R.AsIPAddresses = o.R.AsIPAddresses[:ln-1]
			break
		}
	}

	return nil
}

// AutonomousSystems retrieves all the records using an executor.
func AutonomousSystems(mods ...qm.QueryMod) autonomousSystemQuery {
	mods = append(mods, qm.From("\"autonomous_systems\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"autonomous_systems\".*"})
	}

	return autonomousSystemQuery{q}
}

// FindAutonomousSystem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAutonomousSystem(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*AutonomousSystem, error) {
	autonomousSystemObj := &AutonomousSystem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"autonomous_systems\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, autonomousSystemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from autonomous_systems")
	}

	return autonomousSystemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AutonomousSystem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no autonomous_systems provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(autonomousSystemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	autonomousSystemInsertCacheMut.RLock()
	cache, cached := autonomousSystemInsertCache[key]
	autonomousSystemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			autonomousSystemAllColumns,
			autonomousSystemColumnsWithDefault,
			autonomousSystemColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, autonomousSystemGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(autonomousSystemType, autonomousSystemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(autonomousSystemType, autonomousSystemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"autonomous_systems\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"autonomous_systems\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into autonomous_systems")
	}

	if !cached {
		autonomousSystemInsertCacheMut.Lock()
		autonomousSystemInsertCache[key] = cache
		autonomousSystemInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AutonomousSystem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AutonomousSystem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	autonomousSystemUpdateCacheMut.RLock()
	cache, cached := autonomousSystemUpdateCache[key]
	autonomousSystemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			autonomousSystemAllColumns,
			autonomousSystemPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, autonomousSystemGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update autonomous_systems, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"autonomous_systems\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, autonomousSystemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(autonomousSystemType, autonomousSystemMapping, append(wl, autonomousSystemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update autonomous_systems row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for autonomous_systems")
	}

	if !cached {
		autonomousSystemUpdateCacheMut.Lock()
		autonomousSystemUpdateCache[key] = cache
		autonomousSystemUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q autonomousSystemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for autonomous_systems")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for autonomous_systems")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AutonomousSystemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), autonomousSystemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"autonomous_systems\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, autonomousSystemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in autonomousSystem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all autonomousSystem")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AutonomousSystem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no autonomous_systems provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(autonomousSystemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	autonomousSystemUpsertCacheMut.RLock()
	cache, cached := autonomousSystemUpsertCache[key]
	autonomousSystemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			autonomousSystemAllColumns,
			autonomousSystemColumnsWithDefault,
			autonomousSystemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			autonomousSystemAllColumns,
			autonomousSystemPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, autonomousSystemGeneratedColumns)
		update = strmangle.SetComplement(update, autonomousSystemGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert autonomous_systems, could not build update column list")
		}

		ret := strmangle.SetComplement(autonomousSystemAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(autonomousSystemPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert autonomous_systems, could not build conflict column list")
			}

			conflict = make([]string, len(autonomousSystemPrimaryKeyColumns))
			copy(conflict, autonomousSystemPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"autonomous_systems\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(autonomousSystemType, autonomousSystemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(autonomousSystemType, autonomousSystemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert autonomous_systems")
	}

	if !cached {
		autonomousSystemUpsertCacheMut.Lock()
		autonomousSystemUpsertCache[key] = cache
		autonomousSystemUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AutonomousSystem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AutonomousSystem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AutonomousSystem provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), autonomousSystemPrimaryKeyMapping)
	sql := "DELETE FROM \"autonomous_systems\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from autonomous_systems")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for autonomous_systems")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q autonomousSystemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no autonomousSystemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from autonomous_systems")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for autonomous_systems")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AutonomousSystemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), autonomousSystemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"autonomous_systems\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, autonomousSystemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from autonomousSystem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for autonomous_systems")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AutonomousSystem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAutonomousSystem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AutonomousSystemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AutonomousSystemSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), autonomousSystemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"autonomous_systems\".* FROM \"autonomous_systems\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, autonomousSystemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AutonomousSystemSlice")
	}

	*o = slice

	return nil
}

// AutonomousSystemExists checks if the AutonomousSystem row exists.
func AutonomousSystemExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"autonomous_systems\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if autonomous_systems exists")
	}

	return exists, nil
}

// Exists checks if the AutonomousSystem row exists.
func (o *AutonomousSystem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AutonomousSystemExists(ctx, exec, o.ID)
}
