// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AgentVersions              string
	AutonomousSystems          string
	Cities                     string
	Continents                 string
	Countries                  string
	CrawlSyncStatusCounts      string
	Crawls                     string
	DailyPeerHistory           string
	IPAddresses                string
	MultiAddresses             string
	MultiAddressesXIPAddresses string
	Neighbors                  string
	PeerVisitsIndex            string
	Peers                      string
	PeersStates                string
	PeersXMultiAddresses       string
	Protocols                  string
	ProtocolsSets              string
	Visits                     string
}{
	AgentVersions:              "agent_versions",
	AutonomousSystems:          "autonomous_systems",
	Cities:                     "cities",
	Continents:                 "continents",
	Countries:                  "countries",
	CrawlSyncStatusCounts:      "crawl_sync_status_counts",
	Crawls:                     "crawls",
	DailyPeerHistory:           "daily_peer_history",
	IPAddresses:                "ip_addresses",
	MultiAddresses:             "multi_addresses",
	MultiAddressesXIPAddresses: "multi_addresses_x_ip_addresses",
	Neighbors:                  "neighbors",
	PeerVisitsIndex:            "peer_visits_index",
	Peers:                      "peers",
	PeersStates:                "peers_states",
	PeersXMultiAddresses:       "peers_x_multi_addresses",
	Protocols:                  "protocols",
	ProtocolsSets:              "protocols_sets",
	Visits:                     "visits",
}
