// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// City is an object representing the database table.
type City struct {
	// A unique id that identifies a city.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// The city name.
	CityName string `boil:"city_name" json:"city_name" toml:"city_name" yaml:"city_name"`
	// The country id of the city.
	CountryID null.Int `boil:"country_id" json:"country_id,omitempty" toml:"country_id" yaml:"country_id,omitempty"`
	// The continent id of the city.
	ContinentID null.Int `boil:"continent_id" json:"continent_id,omitempty" toml:"continent_id" yaml:"continent_id,omitempty"`

	R *cityR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L cityL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CityColumns = struct {
	ID          string
	CityName    string
	CountryID   string
	ContinentID string
}{
	ID:          "id",
	CityName:    "city_name",
	CountryID:   "country_id",
	ContinentID: "continent_id",
}

var CityTableColumns = struct {
	ID          string
	CityName    string
	CountryID   string
	ContinentID string
}{
	ID:          "cities.id",
	CityName:    "cities.city_name",
	CountryID:   "cities.country_id",
	ContinentID: "cities.continent_id",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var CityWhere = struct {
	ID          whereHelperint
	CityName    whereHelperstring
	CountryID   whereHelpernull_Int
	ContinentID whereHelpernull_Int
}{
	ID:          whereHelperint{field: "\"cities\".\"id\""},
	CityName:    whereHelperstring{field: "\"cities\".\"city_name\""},
	CountryID:   whereHelpernull_Int{field: "\"cities\".\"country_id\""},
	ContinentID: whereHelpernull_Int{field: "\"cities\".\"continent_id\""},
}

// CityRels is where relationship names are stored.
var CityRels = struct {
	Continent   string
	Country     string
	IPAddresses string
}{
	Continent:   "Continent",
	Country:     "Country",
	IPAddresses: "IPAddresses",
}

// cityR is where relationships are stored.
type cityR struct {
	Continent   *Continent     `boil:"Continent" json:"Continent" toml:"Continent" yaml:"Continent"`
	Country     *Country       `boil:"Country" json:"Country" toml:"Country" yaml:"Country"`
	IPAddresses IPAddressSlice `boil:"IPAddresses" json:"IPAddresses" toml:"IPAddresses" yaml:"IPAddresses"`
}

// NewStruct creates a new relationship struct
func (*cityR) NewStruct() *cityR {
	return &cityR{}
}

func (o *City) GetContinent() *Continent {
	if o == nil {
		return nil
	}

	return o.R.GetContinent()
}

func (r *cityR) GetContinent() *Continent {
	if r == nil {
		return nil
	}

	return r.Continent
}

func (o *City) GetCountry() *Country {
	if o == nil {
		return nil
	}

	return o.R.GetCountry()
}

func (r *cityR) GetCountry() *Country {
	if r == nil {
		return nil
	}

	return r.Country
}

func (o *City) GetIPAddresses() IPAddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIPAddresses()
}

func (r *cityR) GetIPAddresses() IPAddressSlice {
	if r == nil {
		return nil
	}

	return r.IPAddresses
}

// cityL is where Load methods for each relationship are stored.
type cityL struct{}

var (
	cityAllColumns            = []string{"id", "city_name", "country_id", "continent_id"}
	cityColumnsWithoutDefault = []string{"city_name"}
	cityColumnsWithDefault    = []string{"id", "country_id", "continent_id"}
	cityPrimaryKeyColumns     = []string{"id"}
	cityGeneratedColumns      = []string{"id"}
)

type (
	// CitySlice is an alias for a slice of pointers to City.
	// This should almost always be used instead of []City.
	CitySlice []*City

	cityQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	cityType                 = reflect.TypeOf(&City{})
	cityMapping              = queries.MakeStructMapping(cityType)
	cityPrimaryKeyMapping, _ = queries.BindMapping(cityType, cityMapping, cityPrimaryKeyColumns)
	cityInsertCacheMut       sync.RWMutex
	cityInsertCache          = make(map[string]insertCache)
	cityUpdateCacheMut       sync.RWMutex
	cityUpdateCache          = make(map[string]updateCache)
	cityUpsertCacheMut       sync.RWMutex
	cityUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single city record from the query.
func (q cityQuery) One(ctx context.Context, exec boil.ContextExecutor) (*City, error) {
	o := &City{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for cities")
	}

	return o, nil
}

// All returns all City records from the query.
func (q cityQuery) All(ctx context.Context, exec boil.ContextExecutor) (CitySlice, error) {
	var o []*City

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to City slice")
	}

	return o, nil
}

// Count returns the count of all City records in the query.
func (q cityQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count cities rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q cityQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if cities exists")
	}

	return count > 0, nil
}

// Continent pointed to by the foreign key.
func (o *City) Continent(mods ...qm.QueryMod) continentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ContinentID),
	}

	queryMods = append(queryMods, mods...)

	return Continents(queryMods...)
}

// Country pointed to by the foreign key.
func (o *City) Country(mods ...qm.QueryMod) countryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CountryID),
	}

	queryMods = append(queryMods, mods...)

	return Countries(queryMods...)
}

// IPAddresses retrieves all the ip_address's IPAddresses with an executor.
func (o *City) IPAddresses(mods ...qm.QueryMod) ipAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ip_addresses\".\"city_id\"=?", o.ID),
	)

	return IPAddresses(queryMods...)
}

// LoadContinent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (cityL) LoadContinent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCity any, mods queries.Applicator) error {
	var slice []*City
	var object *City

	if singular {
		var ok bool
		object, ok = maybeCity.(*City)
		if !ok {
			object = new(City)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCity)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCity))
			}
		}
	} else {
		s, ok := maybeCity.(*[]*City)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCity)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCity))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &cityR{}
		}
		if !queries.IsNil(object.ContinentID) {
			args[object.ContinentID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &cityR{}
			}

			if !queries.IsNil(obj.ContinentID) {
				args[obj.ContinentID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`continents`),
		qm.WhereIn(`continents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Continent")
	}

	var resultSlice []*Continent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Continent")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for continents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for continents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Continent = foreign
		if foreign.R == nil {
			foreign.R = &continentR{}
		}
		foreign.R.Cities = append(foreign.R.Cities, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ContinentID, foreign.ID) {
				local.R.Continent = foreign
				if foreign.R == nil {
					foreign.R = &continentR{}
				}
				foreign.R.Cities = append(foreign.R.Cities, local)
				break
			}
		}
	}

	return nil
}

// LoadCountry allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (cityL) LoadCountry(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCity any, mods queries.Applicator) error {
	var slice []*City
	var object *City

	if singular {
		var ok bool
		object, ok = maybeCity.(*City)
		if !ok {
			object = new(City)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCity)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCity))
			}
		}
	} else {
		s, ok := maybeCity.(*[]*City)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCity)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCity))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &cityR{}
		}
		if !queries.IsNil(object.CountryID) {
			args[object.CountryID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &cityR{}
			}

			if !queries.IsNil(obj.CountryID) {
				args[obj.CountryID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`countries`),
		qm.WhereIn(`countries.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Country")
	}

	var resultSlice []*Country
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Country")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for countries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for countries")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Country = foreign
		if foreign.R == nil {
			foreign.R = &countryR{}
		}
		foreign.R.Cities = append(foreign.R.Cities, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CountryID, foreign.ID) {
				local.R.Country = foreign
				if foreign.R == nil {
					foreign.R = &countryR{}
				}
				foreign.R.Cities = append(foreign.R.Cities, local)
				break
			}
		}
	}

	return nil
}

// LoadIPAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (cityL) LoadIPAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCity any, mods queries.Applicator) error {
	var slice []*City
	var object *City

	if singular {
		var ok bool
		object, ok = maybeCity.(*City)
		if !ok {
			object = new(City)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCity)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCity))
			}
		}
	} else {
		s, ok := maybeCity.(*[]*City)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCity)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCity))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &cityR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &cityR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ip_addresses`),
		qm.WhereIn(`ip_addresses.city_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ip_addresses")
	}

	var resultSlice []*IPAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ip_addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on ip_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for ip_addresses")
	}

	if singular {
		object.R.IPAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &ipAddressR{}
			}
			foreign.R.City = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CityID) {
				local.R.IPAddresses = append(local.R.IPAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &ipAddressR{}
				}
				foreign.R.City = local
				break
			}
		}
	}

	return nil
}

// SetContinent of the city to the related item.
// Sets o.R.Continent to related.
// Adds o to related.R.Cities.
func (o *City) SetContinent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Continent) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"cities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"continent_id"}),
		strmangle.WhereClause("\"", "\"", 2, cityPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ContinentID, related.ID)
	if o.R == nil {
		o.R = &cityR{
			Continent: related,
		}
	} else {
		o.R.Continent = related
	}

	if related.R == nil {
		related.R = &continentR{
			Cities: CitySlice{o},
		}
	} else {
		related.R.Cities = append(related.R.Cities, o)
	}

	return nil
}

// RemoveContinent relationship.
// Sets o.R.Continent to nil.
// Removes o from all passed in related items' relationships struct.
func (o *City) RemoveContinent(ctx context.Context, exec boil.ContextExecutor, related *Continent) error {
	var err error

	queries.SetScanner(&o.ContinentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("continent_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Continent = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Cities {
		if queries.Equal(o.ContinentID, ri.ContinentID) {
			continue
		}

		ln := len(related.R.Cities)
		if ln > 1 && i < ln-1 {
			related.R.Cities[i] = related.R.Cities[ln-1]
		}
		related.R.Cities = related.R.Cities[:ln-1]
		break
	}
	return nil
}

// SetCountry of the city to the related item.
// Sets o.R.Country to related.
// Adds o to related.R.Cities.
func (o *City) SetCountry(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Country) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"cities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"country_id"}),
		strmangle.WhereClause("\"", "\"", 2, cityPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CountryID, related.ID)
	if o.R == nil {
		o.R = &cityR{
			Country: related,
		}
	} else {
		o.R.Country = related
	}

	if related.R == nil {
		related.R = &countryR{
			Cities: CitySlice{o},
		}
	} else {
		related.R.Cities = append(related.R.Cities, o)
	}

	return nil
}

// RemoveCountry relationship.
// Sets o.R.Country to nil.
// Removes o from all passed in related items' relationships struct.
func (o *City) RemoveCountry(ctx context.Context, exec boil.ContextExecutor, related *Country) error {
	var err error

	queries.SetScanner(&o.CountryID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("country_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Country = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Cities {
		if queries.Equal(o.CountryID, ri.CountryID) {
			continue
		}

		ln := len(related.R.Cities)
		if ln > 1 && i < ln-1 {
			related.R.Cities[i] = related.R.Cities[ln-1]
		}
		related.R.Cities = related.R.Cities[:ln-1]
		break
	}
	return nil
}

// AddIPAddresses adds the given related objects to the existing relationships
// of the city, optionally inserting them as new records.
// Appends related to o.R.IPAddresses.
// Sets related.R.City appropriately.
func (o *City) AddIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CityID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ip_addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"city_id"}),
				strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CityID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &cityR{
			IPAddresses: related,
		}
	} else {
		o.R.IPAddresses = append(o.R.IPAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &ipAddressR{
				City: o,
			}
		} else {
			rel.R.City = o
		}
	}
	return nil
}

// SetIPAddresses removes all previously related items of the
// city replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.City's IPAddresses accordingly.
// Replaces o.R.IPAddresses with related.
// Sets related.R.City's IPAddresses accordingly.
func (o *City) SetIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	query := "update \"ip_addresses\" set \"city_id\" = null where \"city_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.IPAddresses {
			queries.SetScanner(&rel.CityID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.City = nil
		}
		o.R.IPAddresses = nil
	}

	return o.AddIPAddresses(ctx, exec, insert, related...)
}

// RemoveIPAddresses relationships from objects passed in.
// Removes related items from R.IPAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.City.
func (o *City) RemoveIPAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*IPAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CityID, nil)
		if rel.R != nil {
			rel.R.City = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("city_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.IPAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.IPAddresses)
			if ln > 1 && i < ln-1 {
				o.R.IPAddresses[i] = o.R.IPAddresses[ln-1]
			}
			o.R.IPAddresses = o.R.IPAddresses[:ln-1]
			break
		}
	}

	return nil
}

// Cities retrieves all the records using an executor.
func Cities(mods ...qm.QueryMod) cityQuery {
	mods = append(mods, qm.From("\"cities\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"cities\".*"})
	}

	return cityQuery{q}
}

// FindCity retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCity(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*City, error) {
	cityObj := &City{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"cities\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, cityObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from cities")
	}

	return cityObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *City) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cities provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(cityColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	cityInsertCacheMut.RLock()
	cache, cached := cityInsertCache[key]
	cityInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			cityAllColumns,
			cityColumnsWithDefault,
			cityColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, cityGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(cityType, cityMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(cityType, cityMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"cities\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"cities\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into cities")
	}

	if !cached {
		cityInsertCacheMut.Lock()
		cityInsertCache[key] = cache
		cityInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the City.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *City) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	cityUpdateCacheMut.RLock()
	cache, cached := cityUpdateCache[key]
	cityUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			cityAllColumns,
			cityPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, cityGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update cities, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"cities\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, cityPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(cityType, cityMapping, append(wl, cityPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update cities row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for cities")
	}

	if !cached {
		cityUpdateCacheMut.Lock()
		cityUpdateCache[key] = cache
		cityUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q cityQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for cities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for cities")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CitySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"cities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, cityPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in city slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all city")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *City) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no cities provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(cityColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	cityUpsertCacheMut.RLock()
	cache, cached := cityUpsertCache[key]
	cityUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			cityAllColumns,
			cityColumnsWithDefault,
			cityColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			cityAllColumns,
			cityPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, cityGeneratedColumns)
		update = strmangle.SetComplement(update, cityGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert cities, could not build update column list")
		}

		ret := strmangle.SetComplement(cityAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(cityPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert cities, could not build conflict column list")
			}

			conflict = make([]string, len(cityPrimaryKeyColumns))
			copy(conflict, cityPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"cities\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(cityType, cityMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(cityType, cityMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert cities")
	}

	if !cached {
		cityUpsertCacheMut.Lock()
		cityUpsertCache[key] = cache
		cityUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single City record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *City) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no City provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cityPrimaryKeyMapping)
	sql := "DELETE FROM \"cities\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from cities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for cities")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q cityQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no cityQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cities")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CitySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"cities\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, cityPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from city slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cities")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *City) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCity(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CitySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CitySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"cities\".* FROM \"cities\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, cityPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CitySlice")
	}

	*o = slice

	return nil
}

// CityExists checks if the City row exists.
func CityExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"cities\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if cities exists")
	}

	return exists, nil
}

// Exists checks if the City row exists.
func (o *City) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CityExists(ctx, exec, o.ID)
}
