// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Country is an object representing the database table.
type Country struct {
	// A unique id that identifies an autonomous system.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// The ISO code of the country, consisting of two or three characters.
	IsoCode string `boil:"iso_code" json:"iso_code" toml:"iso_code" yaml:"iso_code"`
	// The country name.
	CountryName string `boil:"country_name" json:"country_name" toml:"country_name" yaml:"country_name"`
	// The continent id of the country.
	ContinentID null.Int `boil:"continent_id" json:"continent_id,omitempty" toml:"continent_id" yaml:"continent_id,omitempty"`

	R *countryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L countryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CountryColumns = struct {
	ID          string
	IsoCode     string
	CountryName string
	ContinentID string
}{
	ID:          "id",
	IsoCode:     "iso_code",
	CountryName: "country_name",
	ContinentID: "continent_id",
}

var CountryTableColumns = struct {
	ID          string
	IsoCode     string
	CountryName string
	ContinentID string
}{
	ID:          "countries.id",
	IsoCode:     "countries.iso_code",
	CountryName: "countries.country_name",
	ContinentID: "countries.continent_id",
}

// Generated where

var CountryWhere = struct {
	ID          whereHelperint
	IsoCode     whereHelperstring
	CountryName whereHelperstring
	ContinentID whereHelpernull_Int
}{
	ID:          whereHelperint{field: "\"countries\".\"id\""},
	IsoCode:     whereHelperstring{field: "\"countries\".\"iso_code\""},
	CountryName: whereHelperstring{field: "\"countries\".\"country_name\""},
	ContinentID: whereHelpernull_Int{field: "\"countries\".\"continent_id\""},
}

// CountryRels is where relationship names are stored.
var CountryRels = struct {
	Continent   string
	Cities      string
	IPAddresses string
}{
	Continent:   "Continent",
	Cities:      "Cities",
	IPAddresses: "IPAddresses",
}

// countryR is where relationships are stored.
type countryR struct {
	Continent   *Continent     `boil:"Continent" json:"Continent" toml:"Continent" yaml:"Continent"`
	Cities      CitySlice      `boil:"Cities" json:"Cities" toml:"Cities" yaml:"Cities"`
	IPAddresses IPAddressSlice `boil:"IPAddresses" json:"IPAddresses" toml:"IPAddresses" yaml:"IPAddresses"`
}

// NewStruct creates a new relationship struct
func (*countryR) NewStruct() *countryR {
	return &countryR{}
}

func (o *Country) GetContinent() *Continent {
	if o == nil {
		return nil
	}

	return o.R.GetContinent()
}

func (r *countryR) GetContinent() *Continent {
	if r == nil {
		return nil
	}

	return r.Continent
}

func (o *Country) GetCities() CitySlice {
	if o == nil {
		return nil
	}

	return o.R.GetCities()
}

func (r *countryR) GetCities() CitySlice {
	if r == nil {
		return nil
	}

	return r.Cities
}

func (o *Country) GetIPAddresses() IPAddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIPAddresses()
}

func (r *countryR) GetIPAddresses() IPAddressSlice {
	if r == nil {
		return nil
	}

	return r.IPAddresses
}

// countryL is where Load methods for each relationship are stored.
type countryL struct{}

var (
	countryAllColumns            = []string{"id", "iso_code", "country_name", "continent_id"}
	countryColumnsWithoutDefault = []string{"iso_code", "country_name"}
	countryColumnsWithDefault    = []string{"id", "continent_id"}
	countryPrimaryKeyColumns     = []string{"id"}
	countryGeneratedColumns      = []string{"id"}
)

type (
	// CountrySlice is an alias for a slice of pointers to Country.
	// This should almost always be used instead of []Country.
	CountrySlice []*Country

	countryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	countryType                 = reflect.TypeOf(&Country{})
	countryMapping              = queries.MakeStructMapping(countryType)
	countryPrimaryKeyMapping, _ = queries.BindMapping(countryType, countryMapping, countryPrimaryKeyColumns)
	countryInsertCacheMut       sync.RWMutex
	countryInsertCache          = make(map[string]insertCache)
	countryUpdateCacheMut       sync.RWMutex
	countryUpdateCache          = make(map[string]updateCache)
	countryUpsertCacheMut       sync.RWMutex
	countryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single country record from the query.
func (q countryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Country, error) {
	o := &Country{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for countries")
	}

	return o, nil
}

// All returns all Country records from the query.
func (q countryQuery) All(ctx context.Context, exec boil.ContextExecutor) (CountrySlice, error) {
	var o []*Country

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Country slice")
	}

	return o, nil
}

// Count returns the count of all Country records in the query.
func (q countryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count countries rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q countryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if countries exists")
	}

	return count > 0, nil
}

// Continent pointed to by the foreign key.
func (o *Country) Continent(mods ...qm.QueryMod) continentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ContinentID),
	}

	queryMods = append(queryMods, mods...)

	return Continents(queryMods...)
}

// Cities retrieves all the city's Cities with an executor.
func (o *Country) Cities(mods ...qm.QueryMod) cityQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"cities\".\"country_id\"=?", o.ID),
	)

	return Cities(queryMods...)
}

// IPAddresses retrieves all the ip_address's IPAddresses with an executor.
func (o *Country) IPAddresses(mods ...qm.QueryMod) ipAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ip_addresses\".\"country_id\"=?", o.ID),
	)

	return IPAddresses(queryMods...)
}

// LoadContinent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (countryL) LoadContinent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCountry any, mods queries.Applicator) error {
	var slice []*Country
	var object *Country

	if singular {
		var ok bool
		object, ok = maybeCountry.(*Country)
		if !ok {
			object = new(Country)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCountry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCountry))
			}
		}
	} else {
		s, ok := maybeCountry.(*[]*Country)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCountry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCountry))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &countryR{}
		}
		if !queries.IsNil(object.ContinentID) {
			args[object.ContinentID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &countryR{}
			}

			if !queries.IsNil(obj.ContinentID) {
				args[obj.ContinentID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`continents`),
		qm.WhereIn(`continents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Continent")
	}

	var resultSlice []*Continent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Continent")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for continents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for continents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Continent = foreign
		if foreign.R == nil {
			foreign.R = &continentR{}
		}
		foreign.R.Countries = append(foreign.R.Countries, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ContinentID, foreign.ID) {
				local.R.Continent = foreign
				if foreign.R == nil {
					foreign.R = &continentR{}
				}
				foreign.R.Countries = append(foreign.R.Countries, local)
				break
			}
		}
	}

	return nil
}

// LoadCities allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (countryL) LoadCities(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCountry any, mods queries.Applicator) error {
	var slice []*Country
	var object *Country

	if singular {
		var ok bool
		object, ok = maybeCountry.(*Country)
		if !ok {
			object = new(Country)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCountry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCountry))
			}
		}
	} else {
		s, ok := maybeCountry.(*[]*Country)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCountry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCountry))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &countryR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &countryR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`cities`),
		qm.WhereIn(`cities.country_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load cities")
	}

	var resultSlice []*City
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice cities")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on cities")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for cities")
	}

	if singular {
		object.R.Cities = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &cityR{}
			}
			foreign.R.Country = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CountryID) {
				local.R.Cities = append(local.R.Cities, foreign)
				if foreign.R == nil {
					foreign.R = &cityR{}
				}
				foreign.R.Country = local
				break
			}
		}
	}

	return nil
}

// LoadIPAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (countryL) LoadIPAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCountry any, mods queries.Applicator) error {
	var slice []*Country
	var object *Country

	if singular {
		var ok bool
		object, ok = maybeCountry.(*Country)
		if !ok {
			object = new(Country)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCountry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCountry))
			}
		}
	} else {
		s, ok := maybeCountry.(*[]*Country)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCountry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCountry))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &countryR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &countryR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ip_addresses`),
		qm.WhereIn(`ip_addresses.country_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ip_addresses")
	}

	var resultSlice []*IPAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ip_addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on ip_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for ip_addresses")
	}

	if singular {
		object.R.IPAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &ipAddressR{}
			}
			foreign.R.Country = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CountryID) {
				local.R.IPAddresses = append(local.R.IPAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &ipAddressR{}
				}
				foreign.R.Country = local
				break
			}
		}
	}

	return nil
}

// SetContinent of the country to the related item.
// Sets o.R.Continent to related.
// Adds o to related.R.Countries.
func (o *Country) SetContinent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Continent) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"countries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"continent_id"}),
		strmangle.WhereClause("\"", "\"", 2, countryPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ContinentID, related.ID)
	if o.R == nil {
		o.R = &countryR{
			Continent: related,
		}
	} else {
		o.R.Continent = related
	}

	if related.R == nil {
		related.R = &continentR{
			Countries: CountrySlice{o},
		}
	} else {
		related.R.Countries = append(related.R.Countries, o)
	}

	return nil
}

// RemoveContinent relationship.
// Sets o.R.Continent to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Country) RemoveContinent(ctx context.Context, exec boil.ContextExecutor, related *Continent) error {
	var err error

	queries.SetScanner(&o.ContinentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("continent_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Continent = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Countries {
		if queries.Equal(o.ContinentID, ri.ContinentID) {
			continue
		}

		ln := len(related.R.Countries)
		if ln > 1 && i < ln-1 {
			related.R.Countries[i] = related.R.Countries[ln-1]
		}
		related.R.Countries = related.R.Countries[:ln-1]
		break
	}
	return nil
}

// AddCities adds the given related objects to the existing relationships
// of the country, optionally inserting them as new records.
// Appends related to o.R.Cities.
// Sets related.R.Country appropriately.
func (o *Country) AddCities(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*City) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CountryID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"cities\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"country_id"}),
				strmangle.WhereClause("\"", "\"", 2, cityPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CountryID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &countryR{
			Cities: related,
		}
	} else {
		o.R.Cities = append(o.R.Cities, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &cityR{
				Country: o,
			}
		} else {
			rel.R.Country = o
		}
	}
	return nil
}

// SetCities removes all previously related items of the
// country replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Country's Cities accordingly.
// Replaces o.R.Cities with related.
// Sets related.R.Country's Cities accordingly.
func (o *Country) SetCities(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*City) error {
	query := "update \"cities\" set \"country_id\" = null where \"country_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Cities {
			queries.SetScanner(&rel.CountryID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Country = nil
		}
		o.R.Cities = nil
	}

	return o.AddCities(ctx, exec, insert, related...)
}

// RemoveCities relationships from objects passed in.
// Removes related items from R.Cities (uses pointer comparison, removal does not keep order)
// Sets related.R.Country.
func (o *Country) RemoveCities(ctx context.Context, exec boil.ContextExecutor, related ...*City) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CountryID, nil)
		if rel.R != nil {
			rel.R.Country = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("country_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Cities {
			if rel != ri {
				continue
			}

			ln := len(o.R.Cities)
			if ln > 1 && i < ln-1 {
				o.R.Cities[i] = o.R.Cities[ln-1]
			}
			o.R.Cities = o.R.Cities[:ln-1]
			break
		}
	}

	return nil
}

// AddIPAddresses adds the given related objects to the existing relationships
// of the country, optionally inserting them as new records.
// Appends related to o.R.IPAddresses.
// Sets related.R.Country appropriately.
func (o *Country) AddIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CountryID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ip_addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"country_id"}),
				strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CountryID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &countryR{
			IPAddresses: related,
		}
	} else {
		o.R.IPAddresses = append(o.R.IPAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &ipAddressR{
				Country: o,
			}
		} else {
			rel.R.Country = o
		}
	}
	return nil
}

// SetIPAddresses removes all previously related items of the
// country replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Country's IPAddresses accordingly.
// Replaces o.R.IPAddresses with related.
// Sets related.R.Country's IPAddresses accordingly.
func (o *Country) SetIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	query := "update \"ip_addresses\" set \"country_id\" = null where \"country_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.IPAddresses {
			queries.SetScanner(&rel.CountryID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Country = nil
		}
		o.R.IPAddresses = nil
	}

	return o.AddIPAddresses(ctx, exec, insert, related...)
}

// RemoveIPAddresses relationships from objects passed in.
// Removes related items from R.IPAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.Country.
func (o *Country) RemoveIPAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*IPAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CountryID, nil)
		if rel.R != nil {
			rel.R.Country = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("country_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.IPAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.IPAddresses)
			if ln > 1 && i < ln-1 {
				o.R.IPAddresses[i] = o.R.IPAddresses[ln-1]
			}
			o.R.IPAddresses = o.R.IPAddresses[:ln-1]
			break
		}
	}

	return nil
}

// Countries retrieves all the records using an executor.
func Countries(mods ...qm.QueryMod) countryQuery {
	mods = append(mods, qm.From("\"countries\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"countries\".*"})
	}

	return countryQuery{q}
}

// FindCountry retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCountry(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Country, error) {
	countryObj := &Country{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"countries\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, countryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from countries")
	}

	return countryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Country) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no countries provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(countryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	countryInsertCacheMut.RLock()
	cache, cached := countryInsertCache[key]
	countryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			countryAllColumns,
			countryColumnsWithDefault,
			countryColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, countryGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(countryType, countryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(countryType, countryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"countries\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"countries\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into countries")
	}

	if !cached {
		countryInsertCacheMut.Lock()
		countryInsertCache[key] = cache
		countryInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Country.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Country) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	countryUpdateCacheMut.RLock()
	cache, cached := countryUpdateCache[key]
	countryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			countryAllColumns,
			countryPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, countryGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update countries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"countries\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, countryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(countryType, countryMapping, append(wl, countryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update countries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for countries")
	}

	if !cached {
		countryUpdateCacheMut.Lock()
		countryUpdateCache[key] = cache
		countryUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q countryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for countries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for countries")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CountrySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), countryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"countries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, countryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in country slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all country")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Country) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no countries provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(countryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	countryUpsertCacheMut.RLock()
	cache, cached := countryUpsertCache[key]
	countryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			countryAllColumns,
			countryColumnsWithDefault,
			countryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			countryAllColumns,
			countryPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, countryGeneratedColumns)
		update = strmangle.SetComplement(update, countryGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert countries, could not build update column list")
		}

		ret := strmangle.SetComplement(countryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(countryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert countries, could not build conflict column list")
			}

			conflict = make([]string, len(countryPrimaryKeyColumns))
			copy(conflict, countryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"countries\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(countryType, countryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(countryType, countryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert countries")
	}

	if !cached {
		countryUpsertCacheMut.Lock()
		countryUpsertCache[key] = cache
		countryUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Country record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Country) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Country provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), countryPrimaryKeyMapping)
	sql := "DELETE FROM \"countries\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from countries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for countries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q countryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no countryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from countries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for countries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CountrySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), countryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"countries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, countryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from country slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for countries")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Country) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCountry(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CountrySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CountrySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), countryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"countries\".* FROM \"countries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, countryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CountrySlice")
	}

	*o = slice

	return nil
}

// CountryExists checks if the Country row exists.
func CountryExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"countries\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if countries exists")
	}

	return exists, nil
}

// Exists checks if the Country row exists.
func (o *Country) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CountryExists(ctx, exec, o.ID)
}
