// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Crawl is an object representing the database table.
type Crawl struct {
	// A unique id that identifies a crawl instance.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// Timestamp of when this crawl was started.
	StartedAt time.Time `boil:"started_at" json:"started_at" toml:"started_at" yaml:"started_at"`
	// Timestamp of when this crawl was finished.
	FinishedAt time.Time `boil:"finished_at" json:"finished_at" toml:"finished_at" yaml:"finished_at"`
	// The number of peers that were crawled.
	CrawledPeers null.Int `boil:"crawled_peers" json:"crawled_peers,omitempty" toml:"crawled_peers" yaml:"crawled_peers,omitempty"`
	// The number of peers that were successfully dialed.
	DialablePeers null.Int `boil:"dialable_peers" json:"dialable_peers,omitempty" toml:"dialable_peers" yaml:"dialable_peers,omitempty"`
	// The number of peers that could not be reached.
	UndialablePeers null.Int `boil:"undialable_peers" json:"undialable_peers,omitempty" toml:"undialable_peers" yaml:"undialable_peers,omitempty"`
	// The remaining peers that have yet to be dialed.
	RemainingPeers null.Int `boil:"remaining_peers" json:"remaining_peers,omitempty" toml:"remaining_peers" yaml:"remaining_peers,omitempty"`
	// The version of nebula that was used to perform the crawl.
	Version null.String `boil:"version" json:"version,omitempty" toml:"version" yaml:"version,omitempty"`
	// The state of the crawl.
	State  null.String `boil:"state" json:"state,omitempty" toml:"state" yaml:"state,omitempty"`
	Status string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	// Number of distinct CCV-filtered peers in this crawl
	CCVFilteredPeerCount null.Int `boil:"ccv_filtered_peer_count" json:"ccv_filtered_peer_count,omitempty" toml:"ccv_filtered_peer_count" yaml:"ccv_filtered_peer_count,omitempty"`
	// The CCV used as reference for peer filtering during this crawl
	ReferenceCCV null.String `boil:"reference_ccv" json:"reference_ccv,omitempty" toml:"reference_ccv" yaml:"reference_ccv,omitempty"`

	R *crawlR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L crawlL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CrawlColumns = struct {
	ID                   string
	StartedAt            string
	FinishedAt           string
	CrawledPeers         string
	DialablePeers        string
	UndialablePeers      string
	RemainingPeers       string
	Version              string
	State                string
	Status               string
	CCVFilteredPeerCount string
	ReferenceCCV         string
}{
	ID:                   "id",
	StartedAt:            "started_at",
	FinishedAt:           "finished_at",
	CrawledPeers:         "crawled_peers",
	DialablePeers:        "dialable_peers",
	UndialablePeers:      "undialable_peers",
	RemainingPeers:       "remaining_peers",
	Version:              "version",
	State:                "state",
	Status:               "status",
	CCVFilteredPeerCount: "ccv_filtered_peer_count",
	ReferenceCCV:         "reference_ccv",
}

var CrawlTableColumns = struct {
	ID                   string
	StartedAt            string
	FinishedAt           string
	CrawledPeers         string
	DialablePeers        string
	UndialablePeers      string
	RemainingPeers       string
	Version              string
	State                string
	Status               string
	CCVFilteredPeerCount string
	ReferenceCCV         string
}{
	ID:                   "crawls.id",
	StartedAt:            "crawls.started_at",
	FinishedAt:           "crawls.finished_at",
	CrawledPeers:         "crawls.crawled_peers",
	DialablePeers:        "crawls.dialable_peers",
	UndialablePeers:      "crawls.undialable_peers",
	RemainingPeers:       "crawls.remaining_peers",
	Version:              "crawls.version",
	State:                "crawls.state",
	Status:               "crawls.status",
	CCVFilteredPeerCount: "crawls.ccv_filtered_peer_count",
	ReferenceCCV:         "crawls.reference_ccv",
}

// Generated where

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var CrawlWhere = struct {
	ID                   whereHelperint
	StartedAt            whereHelpertime_Time
	FinishedAt           whereHelpertime_Time
	CrawledPeers         whereHelpernull_Int
	DialablePeers        whereHelpernull_Int
	UndialablePeers      whereHelpernull_Int
	RemainingPeers       whereHelpernull_Int
	Version              whereHelpernull_String
	State                whereHelpernull_String
	Status               whereHelperstring
	CCVFilteredPeerCount whereHelpernull_Int
	ReferenceCCV         whereHelpernull_String
}{
	ID:                   whereHelperint{field: "\"crawls\".\"id\""},
	StartedAt:            whereHelpertime_Time{field: "\"crawls\".\"started_at\""},
	FinishedAt:           whereHelpertime_Time{field: "\"crawls\".\"finished_at\""},
	CrawledPeers:         whereHelpernull_Int{field: "\"crawls\".\"crawled_peers\""},
	DialablePeers:        whereHelpernull_Int{field: "\"crawls\".\"dialable_peers\""},
	UndialablePeers:      whereHelpernull_Int{field: "\"crawls\".\"undialable_peers\""},
	RemainingPeers:       whereHelpernull_Int{field: "\"crawls\".\"remaining_peers\""},
	Version:              whereHelpernull_String{field: "\"crawls\".\"version\""},
	State:                whereHelpernull_String{field: "\"crawls\".\"state\""},
	Status:               whereHelperstring{field: "\"crawls\".\"status\""},
	CCVFilteredPeerCount: whereHelpernull_Int{field: "\"crawls\".\"ccv_filtered_peer_count\""},
	ReferenceCCV:         whereHelpernull_String{field: "\"crawls\".\"reference_ccv\""},
}

// CrawlRels is where relationship names are stored.
var CrawlRels = struct {
	CrawlSyncStatusCount string
	PeerVisitsIndices    string
	Visits               string
}{
	CrawlSyncStatusCount: "CrawlSyncStatusCount",
	PeerVisitsIndices:    "PeerVisitsIndices",
	Visits:               "Visits",
}

// crawlR is where relationships are stored.
type crawlR struct {
	CrawlSyncStatusCount *CrawlSyncStatusCount `boil:"CrawlSyncStatusCount" json:"CrawlSyncStatusCount" toml:"CrawlSyncStatusCount" yaml:"CrawlSyncStatusCount"`
	PeerVisitsIndices    PeerVisitsIndexSlice  `boil:"PeerVisitsIndices" json:"PeerVisitsIndices" toml:"PeerVisitsIndices" yaml:"PeerVisitsIndices"`
	Visits               VisitSlice            `boil:"Visits" json:"Visits" toml:"Visits" yaml:"Visits"`
}

// NewStruct creates a new relationship struct
func (*crawlR) NewStruct() *crawlR {
	return &crawlR{}
}

func (o *Crawl) GetCrawlSyncStatusCount() *CrawlSyncStatusCount {
	if o == nil {
		return nil
	}

	return o.R.GetCrawlSyncStatusCount()
}

func (r *crawlR) GetCrawlSyncStatusCount() *CrawlSyncStatusCount {
	if r == nil {
		return nil
	}

	return r.CrawlSyncStatusCount
}

func (o *Crawl) GetPeerVisitsIndices() PeerVisitsIndexSlice {
	if o == nil {
		return nil
	}

	return o.R.GetPeerVisitsIndices()
}

func (r *crawlR) GetPeerVisitsIndices() PeerVisitsIndexSlice {
	if r == nil {
		return nil
	}

	return r.PeerVisitsIndices
}

func (o *Crawl) GetVisits() VisitSlice {
	if o == nil {
		return nil
	}

	return o.R.GetVisits()
}

func (r *crawlR) GetVisits() VisitSlice {
	if r == nil {
		return nil
	}

	return r.Visits
}

// crawlL is where Load methods for each relationship are stored.
type crawlL struct{}

var (
	crawlAllColumns            = []string{"id", "started_at", "finished_at", "crawled_peers", "dialable_peers", "undialable_peers", "remaining_peers", "version", "state", "status", "ccv_filtered_peer_count", "reference_ccv"}
	crawlColumnsWithoutDefault = []string{"started_at", "finished_at"}
	crawlColumnsWithDefault    = []string{"id", "crawled_peers", "dialable_peers", "undialable_peers", "remaining_peers", "version", "state", "status", "ccv_filtered_peer_count", "reference_ccv"}
	crawlPrimaryKeyColumns     = []string{"id"}
	crawlGeneratedColumns      = []string{"id"}
)

type (
	// CrawlSlice is an alias for a slice of pointers to Crawl.
	// This should almost always be used instead of []Crawl.
	CrawlSlice []*Crawl

	crawlQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	crawlType                 = reflect.TypeOf(&Crawl{})
	crawlMapping              = queries.MakeStructMapping(crawlType)
	crawlPrimaryKeyMapping, _ = queries.BindMapping(crawlType, crawlMapping, crawlPrimaryKeyColumns)
	crawlInsertCacheMut       sync.RWMutex
	crawlInsertCache          = make(map[string]insertCache)
	crawlUpdateCacheMut       sync.RWMutex
	crawlUpdateCache          = make(map[string]updateCache)
	crawlUpsertCacheMut       sync.RWMutex
	crawlUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single crawl record from the query.
func (q crawlQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Crawl, error) {
	o := &Crawl{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for crawls")
	}

	return o, nil
}

// All returns all Crawl records from the query.
func (q crawlQuery) All(ctx context.Context, exec boil.ContextExecutor) (CrawlSlice, error) {
	var o []*Crawl

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Crawl slice")
	}

	return o, nil
}

// Count returns the count of all Crawl records in the query.
func (q crawlQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count crawls rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q crawlQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if crawls exists")
	}

	return count > 0, nil
}

// CrawlSyncStatusCount pointed to by the foreign key.
func (o *Crawl) CrawlSyncStatusCount(mods ...qm.QueryMod) crawlSyncStatusCountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"crawl_id\" = ?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	return CrawlSyncStatusCounts(queryMods...)
}

// PeerVisitsIndices retrieves all the peer_visits_index's PeerVisitsIndices with an executor.
func (o *Crawl) PeerVisitsIndices(mods ...qm.QueryMod) peerVisitsIndexQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"peer_visits_index\".\"crawl_id\"=?", o.ID),
	)

	return PeerVisitsIndices(queryMods...)
}

// Visits retrieves all the visit's Visits with an executor.
func (o *Crawl) Visits(mods ...qm.QueryMod) visitQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"visits\".\"crawl_id\"=?", o.ID),
	)

	return Visits(queryMods...)
}

// LoadCrawlSyncStatusCount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-1 relationship.
func (crawlL) LoadCrawlSyncStatusCount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawl any, mods queries.Applicator) error {
	var slice []*Crawl
	var object *Crawl

	if singular {
		var ok bool
		object, ok = maybeCrawl.(*Crawl)
		if !ok {
			object = new(Crawl)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawl))
			}
		}
	} else {
		s, ok := maybeCrawl.(*[]*Crawl)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawl))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlR{}
			}

			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`crawl_sync_status_counts`),
		qm.WhereIn(`crawl_sync_status_counts.crawl_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load CrawlSyncStatusCount")
	}

	var resultSlice []*CrawlSyncStatusCount
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice CrawlSyncStatusCount")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for crawl_sync_status_counts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for crawl_sync_status_counts")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CrawlSyncStatusCount = foreign
		if foreign.R == nil {
			foreign.R = &crawlSyncStatusCountR{}
		}
		foreign.R.Crawl = object
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.CrawlID {
				local.R.CrawlSyncStatusCount = foreign
				if foreign.R == nil {
					foreign.R = &crawlSyncStatusCountR{}
				}
				foreign.R.Crawl = local
				break
			}
		}
	}

	return nil
}

// LoadPeerVisitsIndices allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (crawlL) LoadPeerVisitsIndices(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawl any, mods queries.Applicator) error {
	var slice []*Crawl
	var object *Crawl

	if singular {
		var ok bool
		object, ok = maybeCrawl.(*Crawl)
		if !ok {
			object = new(Crawl)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawl))
			}
		}
	} else {
		s, ok := maybeCrawl.(*[]*Crawl)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawl))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`peer_visits_index`),
		qm.WhereIn(`peer_visits_index.crawl_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load peer_visits_index")
	}

	var resultSlice []*PeerVisitsIndex
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice peer_visits_index")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on peer_visits_index")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for peer_visits_index")
	}

	if singular {
		object.R.PeerVisitsIndices = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &peerVisitsIndexR{}
			}
			foreign.R.Crawl = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.CrawlID {
				local.R.PeerVisitsIndices = append(local.R.PeerVisitsIndices, foreign)
				if foreign.R == nil {
					foreign.R = &peerVisitsIndexR{}
				}
				foreign.R.Crawl = local
				break
			}
		}
	}

	return nil
}

// LoadVisits allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (crawlL) LoadVisits(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawl any, mods queries.Applicator) error {
	var slice []*Crawl
	var object *Crawl

	if singular {
		var ok bool
		object, ok = maybeCrawl.(*Crawl)
		if !ok {
			object = new(Crawl)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawl))
			}
		}
	} else {
		s, ok := maybeCrawl.(*[]*Crawl)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawl))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`visits`),
		qm.WhereIn(`visits.crawl_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load visits")
	}

	var resultSlice []*Visit
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice visits")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on visits")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for visits")
	}

	if singular {
		object.R.Visits = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &visitR{}
			}
			foreign.R.Crawl = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CrawlID) {
				local.R.Visits = append(local.R.Visits, foreign)
				if foreign.R == nil {
					foreign.R = &visitR{}
				}
				foreign.R.Crawl = local
				break
			}
		}
	}

	return nil
}

// SetCrawlSyncStatusCount of the crawl to the related item.
// Sets o.R.CrawlSyncStatusCount to related.
// Adds o to related.R.Crawl.
func (o *Crawl) SetCrawlSyncStatusCount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *CrawlSyncStatusCount) error {
	var err error

	if insert {
		related.CrawlID = o.ID

		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"crawl_sync_status_counts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"crawl_id"}),
			strmangle.WhereClause("\"", "\"", 2, crawlSyncStatusCountPrimaryKeyColumns),
		)
		values := []any{o.ID, related.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, updateQuery)
			fmt.Fprintln(writer, values)
		}
		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.CrawlID = o.ID
	}

	if o.R == nil {
		o.R = &crawlR{
			CrawlSyncStatusCount: related,
		}
	} else {
		o.R.CrawlSyncStatusCount = related
	}

	if related.R == nil {
		related.R = &crawlSyncStatusCountR{
			Crawl: o,
		}
	} else {
		related.R.Crawl = o
	}
	return nil
}

// AddPeerVisitsIndices adds the given related objects to the existing relationships
// of the crawl, optionally inserting them as new records.
// Appends related to o.R.PeerVisitsIndices.
// Sets related.R.Crawl appropriately.
func (o *Crawl) AddPeerVisitsIndices(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PeerVisitsIndex) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CrawlID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"peer_visits_index\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"crawl_id"}),
				strmangle.WhereClause("\"", "\"", 2, peerVisitsIndexPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.CrawlID, rel.VisitID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CrawlID = o.ID
		}
	}

	if o.R == nil {
		o.R = &crawlR{
			PeerVisitsIndices: related,
		}
	} else {
		o.R.PeerVisitsIndices = append(o.R.PeerVisitsIndices, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &peerVisitsIndexR{
				Crawl: o,
			}
		} else {
			rel.R.Crawl = o
		}
	}
	return nil
}

// AddVisits adds the given related objects to the existing relationships
// of the crawl, optionally inserting them as new records.
// Appends related to o.R.Visits.
// Sets related.R.Crawl appropriately.
func (o *Crawl) AddVisits(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Visit) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CrawlID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"visits\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"crawl_id"}),
				strmangle.WhereClause("\"", "\"", 2, visitPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID, rel.VisitStartedAt}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CrawlID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &crawlR{
			Visits: related,
		}
	} else {
		o.R.Visits = append(o.R.Visits, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &visitR{
				Crawl: o,
			}
		} else {
			rel.R.Crawl = o
		}
	}
	return nil
}

// SetVisits removes all previously related items of the
// crawl replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Crawl's Visits accordingly.
// Replaces o.R.Visits with related.
// Sets related.R.Crawl's Visits accordingly.
func (o *Crawl) SetVisits(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Visit) error {
	query := "update \"visits\" set \"crawl_id\" = null where \"crawl_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Visits {
			queries.SetScanner(&rel.CrawlID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Crawl = nil
		}
		o.R.Visits = nil
	}

	return o.AddVisits(ctx, exec, insert, related...)
}

// RemoveVisits relationships from objects passed in.
// Removes related items from R.Visits (uses pointer comparison, removal does not keep order)
// Sets related.R.Crawl.
func (o *Crawl) RemoveVisits(ctx context.Context, exec boil.ContextExecutor, related ...*Visit) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CrawlID, nil)
		if rel.R != nil {
			rel.R.Crawl = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("crawl_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Visits {
			if rel != ri {
				continue
			}

			ln := len(o.R.Visits)
			if ln > 1 && i < ln-1 {
				o.R.Visits[i] = o.R.Visits[ln-1]
			}
			o.R.Visits = o.R.Visits[:ln-1]
			break
		}
	}

	return nil
}

// Crawls retrieves all the records using an executor.
func Crawls(mods ...qm.QueryMod) crawlQuery {
	mods = append(mods, qm.From("\"crawls\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"crawls\".*"})
	}

	return crawlQuery{q}
}

// FindCrawl retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCrawl(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Crawl, error) {
	crawlObj := &Crawl{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"crawls\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, crawlObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from crawls")
	}

	return crawlObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Crawl) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no crawls provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(crawlColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	crawlInsertCacheMut.RLock()
	cache, cached := crawlInsertCache[key]
	crawlInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			crawlAllColumns,
			crawlColumnsWithDefault,
			crawlColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, crawlGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(crawlType, crawlMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(crawlType, crawlMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"crawls\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"crawls\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into crawls")
	}

	if !cached {
		crawlInsertCacheMut.Lock()
		crawlInsertCache[key] = cache
		crawlInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Crawl.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Crawl) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	crawlUpdateCacheMut.RLock()
	cache, cached := crawlUpdateCache[key]
	crawlUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			crawlAllColumns,
			crawlPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, crawlGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update crawls, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"crawls\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, crawlPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(crawlType, crawlMapping, append(wl, crawlPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update crawls row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for crawls")
	}

	if !cached {
		crawlUpdateCacheMut.Lock()
		crawlUpdateCache[key] = cache
		crawlUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q crawlQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for crawls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for crawls")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CrawlSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"crawls\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, crawlPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in crawl slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all crawl")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Crawl) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no crawls provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	crawlUpsertCacheMut.RLock()
	cache, cached := crawlUpsertCache[key]
	crawlUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			crawlAllColumns,
			crawlColumnsWithDefault,
			crawlColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			crawlAllColumns,
			crawlPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, crawlGeneratedColumns)
		update = strmangle.SetComplement(update, crawlGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert crawls, could not build update column list")
		}

		ret := strmangle.SetComplement(crawlAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(crawlPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert crawls, could not build conflict column list")
			}

			conflict = make([]string, len(crawlPrimaryKeyColumns))
			copy(conflict, crawlPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"crawls\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(crawlType, crawlMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(crawlType, crawlMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert crawls")
	}

	if !cached {
		crawlUpsertCacheMut.Lock()
		crawlUpsertCache[key] = cache
		crawlUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Crawl record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Crawl) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Crawl provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), crawlPrimaryKeyMapping)
	sql := "DELETE FROM \"crawls\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from crawls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for crawls")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q crawlQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no crawlQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from crawls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for crawls")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CrawlSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"crawls\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from crawl slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for crawls")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Crawl) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCrawl(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CrawlSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CrawlSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"crawls\".* FROM \"crawls\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CrawlSlice")
	}

	*o = slice

	return nil
}

// CrawlExists checks if the Crawl row exists.
func CrawlExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"crawls\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if crawls exists")
	}

	return exists, nil
}

// Exists checks if the Crawl row exists.
func (o *Crawl) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CrawlExists(ctx, exec, o.ID)
}
