// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// IPAddress is an object representing the database table.
type IPAddress struct {
	// A unique id that identifies this ip address.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// The country that the IP address belongs to.
	CountryID null.Int `boil:"country_id" json:"country_id,omitempty" toml:"country_id" yaml:"country_id,omitempty"`
	// The continent that the IP address belongs to.
	ContinentID null.Int `boil:"continent_id" json:"continent_id,omitempty" toml:"continent_id" yaml:"continent_id,omitempty"`
	// The city that the IP address belongs to.
	CityID null.Int `boil:"city_id" json:"city_id,omitempty" toml:"city_id" yaml:"city_id,omitempty"`
	// The autonomous system that the IP address belongs to.
	AsID null.Int `boil:"as_id" json:"as_id,omitempty" toml:"as_id" yaml:"as_id,omitempty"`
	// When was this IP address created.
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// When was this IP address last updated.
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	// The latitude of the IP address.
	Latitude null.Float64 `boil:"latitude" json:"latitude,omitempty" toml:"latitude" yaml:"latitude,omitempty"`
	// The longitude of the IP address.
	Longitude null.Float64 `boil:"longitude" json:"longitude,omitempty" toml:"longitude" yaml:"longitude,omitempty"`
	// The IP address derived from a multi address.
	IPAddress string `boil:"ip_address" json:"ip_address" toml:"ip_address" yaml:"ip_address"`
	// The port used to connect to the IP address.
	Port int `boil:"port" json:"port" toml:"port" yaml:"port"`

	R *ipAddressR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L ipAddressL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IPAddressColumns = struct {
	ID          string
	CountryID   string
	ContinentID string
	CityID      string
	AsID        string
	CreatedAt   string
	UpdatedAt   string
	Latitude    string
	Longitude   string
	IPAddress   string
	Port        string
}{
	ID:          "id",
	CountryID:   "country_id",
	ContinentID: "continent_id",
	CityID:      "city_id",
	AsID:        "as_id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	Latitude:    "latitude",
	Longitude:   "longitude",
	IPAddress:   "ip_address",
	Port:        "port",
}

var IPAddressTableColumns = struct {
	ID          string
	CountryID   string
	ContinentID string
	CityID      string
	AsID        string
	CreatedAt   string
	UpdatedAt   string
	Latitude    string
	Longitude   string
	IPAddress   string
	Port        string
}{
	ID:          "ip_addresses.id",
	CountryID:   "ip_addresses.country_id",
	ContinentID: "ip_addresses.continent_id",
	CityID:      "ip_addresses.city_id",
	AsID:        "ip_addresses.as_id",
	CreatedAt:   "ip_addresses.created_at",
	UpdatedAt:   "ip_addresses.updated_at",
	Latitude:    "ip_addresses.latitude",
	Longitude:   "ip_addresses.longitude",
	IPAddress:   "ip_addresses.ip_address",
	Port:        "ip_addresses.port",
}

// Generated where

type whereHelpernull_Float64 struct{ field string }

func (w whereHelpernull_Float64) EQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Float64) NEQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Float64) LT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Float64) LTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Float64) GT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Float64) GTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Float64) IN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Float64) NIN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Float64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Float64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var IPAddressWhere = struct {
	ID          whereHelperint
	CountryID   whereHelpernull_Int
	ContinentID whereHelpernull_Int
	CityID      whereHelpernull_Int
	AsID        whereHelpernull_Int
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
	Latitude    whereHelpernull_Float64
	Longitude   whereHelpernull_Float64
	IPAddress   whereHelperstring
	Port        whereHelperint
}{
	ID:          whereHelperint{field: "\"ip_addresses\".\"id\""},
	CountryID:   whereHelpernull_Int{field: "\"ip_addresses\".\"country_id\""},
	ContinentID: whereHelpernull_Int{field: "\"ip_addresses\".\"continent_id\""},
	CityID:      whereHelpernull_Int{field: "\"ip_addresses\".\"city_id\""},
	AsID:        whereHelpernull_Int{field: "\"ip_addresses\".\"as_id\""},
	CreatedAt:   whereHelpertime_Time{field: "\"ip_addresses\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"ip_addresses\".\"updated_at\""},
	Latitude:    whereHelpernull_Float64{field: "\"ip_addresses\".\"latitude\""},
	Longitude:   whereHelpernull_Float64{field: "\"ip_addresses\".\"longitude\""},
	IPAddress:   whereHelperstring{field: "\"ip_addresses\".\"ip_address\""},
	Port:        whereHelperint{field: "\"ip_addresses\".\"port\""},
}

// IPAddressRels is where relationship names are stored.
var IPAddressRels = struct {
	As             string
	City           string
	Continent      string
	Country        string
	MultiAddresses string
}{
	As:             "As",
	City:           "City",
	Continent:      "Continent",
	Country:        "Country",
	MultiAddresses: "MultiAddresses",
}

// ipAddressR is where relationships are stored.
type ipAddressR struct {
	As             *AutonomousSystem `boil:"As" json:"As" toml:"As" yaml:"As"`
	City           *City             `boil:"City" json:"City" toml:"City" yaml:"City"`
	Continent      *Continent        `boil:"Continent" json:"Continent" toml:"Continent" yaml:"Continent"`
	Country        *Country          `boil:"Country" json:"Country" toml:"Country" yaml:"Country"`
	MultiAddresses MultiAddressSlice `boil:"MultiAddresses" json:"MultiAddresses" toml:"MultiAddresses" yaml:"MultiAddresses"`
}

// NewStruct creates a new relationship struct
func (*ipAddressR) NewStruct() *ipAddressR {
	return &ipAddressR{}
}

func (o *IPAddress) GetAs() *AutonomousSystem {
	if o == nil {
		return nil
	}

	return o.R.GetAs()
}

func (r *ipAddressR) GetAs() *AutonomousSystem {
	if r == nil {
		return nil
	}

	return r.As
}

func (o *IPAddress) GetCity() *City {
	if o == nil {
		return nil
	}

	return o.R.GetCity()
}

func (r *ipAddressR) GetCity() *City {
	if r == nil {
		return nil
	}

	return r.City
}

func (o *IPAddress) GetContinent() *Continent {
	if o == nil {
		return nil
	}

	return o.R.GetContinent()
}

func (r *ipAddressR) GetContinent() *Continent {
	if r == nil {
		return nil
	}

	return r.Continent
}

func (o *IPAddress) GetCountry() *Country {
	if o == nil {
		return nil
	}

	return o.R.GetCountry()
}

func (r *ipAddressR) GetCountry() *Country {
	if r == nil {
		return nil
	}

	return r.Country
}

func (o *IPAddress) GetMultiAddresses() MultiAddressSlice {
	if o == nil {
		return nil
	}

	return o.R.GetMultiAddresses()
}

func (r *ipAddressR) GetMultiAddresses() MultiAddressSlice {
	if r == nil {
		return nil
	}

	return r.MultiAddresses
}

// ipAddressL is where Load methods for each relationship are stored.
type ipAddressL struct{}

var (
	ipAddressAllColumns            = []string{"id", "country_id", "continent_id", "city_id", "as_id", "created_at", "updated_at", "latitude", "longitude", "ip_address", "port"}
	ipAddressColumnsWithoutDefault = []string{"created_at", "updated_at", "ip_address", "port"}
	ipAddressColumnsWithDefault    = []string{"id", "country_id", "continent_id", "city_id", "as_id", "latitude", "longitude"}
	ipAddressPrimaryKeyColumns     = []string{"id"}
	ipAddressGeneratedColumns      = []string{"id"}
)

type (
	// IPAddressSlice is an alias for a slice of pointers to IPAddress.
	// This should almost always be used instead of []IPAddress.
	IPAddressSlice []*IPAddress

	ipAddressQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	ipAddressType                 = reflect.TypeOf(&IPAddress{})
	ipAddressMapping              = queries.MakeStructMapping(ipAddressType)
	ipAddressPrimaryKeyMapping, _ = queries.BindMapping(ipAddressType, ipAddressMapping, ipAddressPrimaryKeyColumns)
	ipAddressInsertCacheMut       sync.RWMutex
	ipAddressInsertCache          = make(map[string]insertCache)
	ipAddressUpdateCacheMut       sync.RWMutex
	ipAddressUpdateCache          = make(map[string]updateCache)
	ipAddressUpsertCacheMut       sync.RWMutex
	ipAddressUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single ipAddress record from the query.
func (q ipAddressQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IPAddress, error) {
	o := &IPAddress{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for ip_addresses")
	}

	return o, nil
}

// All returns all IPAddress records from the query.
func (q ipAddressQuery) All(ctx context.Context, exec boil.ContextExecutor) (IPAddressSlice, error) {
	var o []*IPAddress

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to IPAddress slice")
	}

	return o, nil
}

// Count returns the count of all IPAddress records in the query.
func (q ipAddressQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count ip_addresses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q ipAddressQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if ip_addresses exists")
	}

	return count > 0, nil
}

// As pointed to by the foreign key.
func (o *IPAddress) As(mods ...qm.QueryMod) autonomousSystemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AsID),
	}

	queryMods = append(queryMods, mods...)

	return AutonomousSystems(queryMods...)
}

// City pointed to by the foreign key.
func (o *IPAddress) City(mods ...qm.QueryMod) cityQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CityID),
	}

	queryMods = append(queryMods, mods...)

	return Cities(queryMods...)
}

// Continent pointed to by the foreign key.
func (o *IPAddress) Continent(mods ...qm.QueryMod) continentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ContinentID),
	}

	queryMods = append(queryMods, mods...)

	return Continents(queryMods...)
}

// Country pointed to by the foreign key.
func (o *IPAddress) Country(mods ...qm.QueryMod) countryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CountryID),
	}

	queryMods = append(queryMods, mods...)

	return Countries(queryMods...)
}

// MultiAddresses retrieves all the multi_address's MultiAddresses with an executor.
func (o *IPAddress) MultiAddresses(mods ...qm.QueryMod) multiAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"multi_addresses_x_ip_addresses\" on \"multi_addresses\".\"id\" = \"multi_addresses_x_ip_addresses\".\"multi_address_id\""),
		qm.Where("\"multi_addresses_x_ip_addresses\".\"ip_address_id\"=?", o.ID),
	)

	return MultiAddresses(queryMods...)
}

// LoadAs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (ipAddressL) LoadAs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIPAddress any, mods queries.Applicator) error {
	var slice []*IPAddress
	var object *IPAddress

	if singular {
		var ok bool
		object, ok = maybeIPAddress.(*IPAddress)
		if !ok {
			object = new(IPAddress)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIPAddress))
			}
		}
	} else {
		s, ok := maybeIPAddress.(*[]*IPAddress)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIPAddress))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &ipAddressR{}
		}
		if !queries.IsNil(object.AsID) {
			args[object.AsID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &ipAddressR{}
			}

			if !queries.IsNil(obj.AsID) {
				args[obj.AsID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`autonomous_systems`),
		qm.WhereIn(`autonomous_systems.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AutonomousSystem")
	}

	var resultSlice []*AutonomousSystem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AutonomousSystem")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for autonomous_systems")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for autonomous_systems")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.As = foreign
		if foreign.R == nil {
			foreign.R = &autonomousSystemR{}
		}
		foreign.R.AsIPAddresses = append(foreign.R.AsIPAddresses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AsID, foreign.ID) {
				local.R.As = foreign
				if foreign.R == nil {
					foreign.R = &autonomousSystemR{}
				}
				foreign.R.AsIPAddresses = append(foreign.R.AsIPAddresses, local)
				break
			}
		}
	}

	return nil
}

// LoadCity allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (ipAddressL) LoadCity(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIPAddress any, mods queries.Applicator) error {
	var slice []*IPAddress
	var object *IPAddress

	if singular {
		var ok bool
		object, ok = maybeIPAddress.(*IPAddress)
		if !ok {
			object = new(IPAddress)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIPAddress))
			}
		}
	} else {
		s, ok := maybeIPAddress.(*[]*IPAddress)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIPAddress))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &ipAddressR{}
		}
		if !queries.IsNil(object.CityID) {
			args[object.CityID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &ipAddressR{}
			}

			if !queries.IsNil(obj.CityID) {
				args[obj.CityID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`cities`),
		qm.WhereIn(`cities.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load City")
	}

	var resultSlice []*City
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice City")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for cities")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for cities")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.City = foreign
		if foreign.R == nil {
			foreign.R = &cityR{}
		}
		foreign.R.IPAddresses = append(foreign.R.IPAddresses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CityID, foreign.ID) {
				local.R.City = foreign
				if foreign.R == nil {
					foreign.R = &cityR{}
				}
				foreign.R.IPAddresses = append(foreign.R.IPAddresses, local)
				break
			}
		}
	}

	return nil
}

// LoadContinent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (ipAddressL) LoadContinent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIPAddress any, mods queries.Applicator) error {
	var slice []*IPAddress
	var object *IPAddress

	if singular {
		var ok bool
		object, ok = maybeIPAddress.(*IPAddress)
		if !ok {
			object = new(IPAddress)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIPAddress))
			}
		}
	} else {
		s, ok := maybeIPAddress.(*[]*IPAddress)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIPAddress))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &ipAddressR{}
		}
		if !queries.IsNil(object.ContinentID) {
			args[object.ContinentID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &ipAddressR{}
			}

			if !queries.IsNil(obj.ContinentID) {
				args[obj.ContinentID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`continents`),
		qm.WhereIn(`continents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Continent")
	}

	var resultSlice []*Continent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Continent")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for continents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for continents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Continent = foreign
		if foreign.R == nil {
			foreign.R = &continentR{}
		}
		foreign.R.IPAddresses = append(foreign.R.IPAddresses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ContinentID, foreign.ID) {
				local.R.Continent = foreign
				if foreign.R == nil {
					foreign.R = &continentR{}
				}
				foreign.R.IPAddresses = append(foreign.R.IPAddresses, local)
				break
			}
		}
	}

	return nil
}

// LoadCountry allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (ipAddressL) LoadCountry(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIPAddress any, mods queries.Applicator) error {
	var slice []*IPAddress
	var object *IPAddress

	if singular {
		var ok bool
		object, ok = maybeIPAddress.(*IPAddress)
		if !ok {
			object = new(IPAddress)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIPAddress))
			}
		}
	} else {
		s, ok := maybeIPAddress.(*[]*IPAddress)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIPAddress))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &ipAddressR{}
		}
		if !queries.IsNil(object.CountryID) {
			args[object.CountryID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &ipAddressR{}
			}

			if !queries.IsNil(obj.CountryID) {
				args[obj.CountryID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`countries`),
		qm.WhereIn(`countries.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Country")
	}

	var resultSlice []*Country
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Country")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for countries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for countries")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Country = foreign
		if foreign.R == nil {
			foreign.R = &countryR{}
		}
		foreign.R.IPAddresses = append(foreign.R.IPAddresses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CountryID, foreign.ID) {
				local.R.Country = foreign
				if foreign.R == nil {
					foreign.R = &countryR{}
				}
				foreign.R.IPAddresses = append(foreign.R.IPAddresses, local)
				break
			}
		}
	}

	return nil
}

// LoadMultiAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (ipAddressL) LoadMultiAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIPAddress any, mods queries.Applicator) error {
	var slice []*IPAddress
	var object *IPAddress

	if singular {
		var ok bool
		object, ok = maybeIPAddress.(*IPAddress)
		if !ok {
			object = new(IPAddress)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIPAddress))
			}
		}
	} else {
		s, ok := maybeIPAddress.(*[]*IPAddress)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIPAddress)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIPAddress))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &ipAddressR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &ipAddressR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"multi_addresses\".\"id\", \"multi_addresses\".\"maddr\", \"multi_addresses\".\"created_at\", \"a\".\"ip_address_id\""),
		qm.From("\"multi_addresses\""),
		qm.InnerJoin("\"multi_addresses_x_ip_addresses\" as \"a\" on \"multi_addresses\".\"id\" = \"a\".\"multi_address_id\""),
		qm.WhereIn("\"a\".\"ip_address_id\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load multi_addresses")
	}

	var resultSlice []*MultiAddress

	var localJoinCols []int
	for results.Next() {
		one := new(MultiAddress)
		var localJoinCol int

		err = results.Scan(&one.ID, &one.Maddr, &one.CreatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for multi_addresses")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice multi_addresses")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on multi_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for multi_addresses")
	}

	if singular {
		object.R.MultiAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &multiAddressR{}
			}
			foreign.R.IPAddresses = append(foreign.R.IPAddresses, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.MultiAddresses = append(local.R.MultiAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &multiAddressR{}
				}
				foreign.R.IPAddresses = append(foreign.R.IPAddresses, local)
				break
			}
		}
	}

	return nil
}

// SetAs of the ipAddress to the related item.
// Sets o.R.As to related.
// Adds o to related.R.AsIPAddresses.
func (o *IPAddress) SetAs(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AutonomousSystem) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ip_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"as_id"}),
		strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AsID, related.ID)
	if o.R == nil {
		o.R = &ipAddressR{
			As: related,
		}
	} else {
		o.R.As = related
	}

	if related.R == nil {
		related.R = &autonomousSystemR{
			AsIPAddresses: IPAddressSlice{o},
		}
	} else {
		related.R.AsIPAddresses = append(related.R.AsIPAddresses, o)
	}

	return nil
}

// RemoveAs relationship.
// Sets o.R.As to nil.
// Removes o from all passed in related items' relationships struct.
func (o *IPAddress) RemoveAs(ctx context.Context, exec boil.ContextExecutor, related *AutonomousSystem) error {
	var err error

	queries.SetScanner(&o.AsID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("as_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.As = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.AsIPAddresses {
		if queries.Equal(o.AsID, ri.AsID) {
			continue
		}

		ln := len(related.R.AsIPAddresses)
		if ln > 1 && i < ln-1 {
			related.R.AsIPAddresses[i] = related.R.AsIPAddresses[ln-1]
		}
		related.R.AsIPAddresses = related.R.AsIPAddresses[:ln-1]
		break
	}
	return nil
}

// SetCity of the ipAddress to the related item.
// Sets o.R.City to related.
// Adds o to related.R.IPAddresses.
func (o *IPAddress) SetCity(ctx context.Context, exec boil.ContextExecutor, insert bool, related *City) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ip_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"city_id"}),
		strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CityID, related.ID)
	if o.R == nil {
		o.R = &ipAddressR{
			City: related,
		}
	} else {
		o.R.City = related
	}

	if related.R == nil {
		related.R = &cityR{
			IPAddresses: IPAddressSlice{o},
		}
	} else {
		related.R.IPAddresses = append(related.R.IPAddresses, o)
	}

	return nil
}

// RemoveCity relationship.
// Sets o.R.City to nil.
// Removes o from all passed in related items' relationships struct.
func (o *IPAddress) RemoveCity(ctx context.Context, exec boil.ContextExecutor, related *City) error {
	var err error

	queries.SetScanner(&o.CityID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("city_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.City = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.IPAddresses {
		if queries.Equal(o.CityID, ri.CityID) {
			continue
		}

		ln := len(related.R.IPAddresses)
		if ln > 1 && i < ln-1 {
			related.R.IPAddresses[i] = related.R.IPAddresses[ln-1]
		}
		related.R.IPAddresses = related.R.IPAddresses[:ln-1]
		break
	}
	return nil
}

// SetContinent of the ipAddress to the related item.
// Sets o.R.Continent to related.
// Adds o to related.R.IPAddresses.
func (o *IPAddress) SetContinent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Continent) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ip_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"continent_id"}),
		strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ContinentID, related.ID)
	if o.R == nil {
		o.R = &ipAddressR{
			Continent: related,
		}
	} else {
		o.R.Continent = related
	}

	if related.R == nil {
		related.R = &continentR{
			IPAddresses: IPAddressSlice{o},
		}
	} else {
		related.R.IPAddresses = append(related.R.IPAddresses, o)
	}

	return nil
}

// RemoveContinent relationship.
// Sets o.R.Continent to nil.
// Removes o from all passed in related items' relationships struct.
func (o *IPAddress) RemoveContinent(ctx context.Context, exec boil.ContextExecutor, related *Continent) error {
	var err error

	queries.SetScanner(&o.ContinentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("continent_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Continent = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.IPAddresses {
		if queries.Equal(o.ContinentID, ri.ContinentID) {
			continue
		}

		ln := len(related.R.IPAddresses)
		if ln > 1 && i < ln-1 {
			related.R.IPAddresses[i] = related.R.IPAddresses[ln-1]
		}
		related.R.IPAddresses = related.R.IPAddresses[:ln-1]
		break
	}
	return nil
}

// SetCountry of the ipAddress to the related item.
// Sets o.R.Country to related.
// Adds o to related.R.IPAddresses.
func (o *IPAddress) SetCountry(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Country) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ip_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"country_id"}),
		strmangle.WhereClause("\"", "\"", 2, ipAddressPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CountryID, related.ID)
	if o.R == nil {
		o.R = &ipAddressR{
			Country: related,
		}
	} else {
		o.R.Country = related
	}

	if related.R == nil {
		related.R = &countryR{
			IPAddresses: IPAddressSlice{o},
		}
	} else {
		related.R.IPAddresses = append(related.R.IPAddresses, o)
	}

	return nil
}

// RemoveCountry relationship.
// Sets o.R.Country to nil.
// Removes o from all passed in related items' relationships struct.
func (o *IPAddress) RemoveCountry(ctx context.Context, exec boil.ContextExecutor, related *Country) error {
	var err error

	queries.SetScanner(&o.CountryID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("country_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Country = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.IPAddresses {
		if queries.Equal(o.CountryID, ri.CountryID) {
			continue
		}

		ln := len(related.R.IPAddresses)
		if ln > 1 && i < ln-1 {
			related.R.IPAddresses[i] = related.R.IPAddresses[ln-1]
		}
		related.R.IPAddresses = related.R.IPAddresses[:ln-1]
		break
	}
	return nil
}

// AddMultiAddresses adds the given related objects to the existing relationships
// of the ip_address, optionally inserting them as new records.
// Appends related to o.R.MultiAddresses.
// Sets related.R.IPAddresses appropriately.
func (o *IPAddress) AddMultiAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MultiAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"multi_addresses_x_ip_addresses\" (\"ip_address_id\", \"multi_address_id\") values ($1, $2)"
		values := []any{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &ipAddressR{
			MultiAddresses: related,
		}
	} else {
		o.R.MultiAddresses = append(o.R.MultiAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &multiAddressR{
				IPAddresses: IPAddressSlice{o},
			}
		} else {
			rel.R.IPAddresses = append(rel.R.IPAddresses, o)
		}
	}
	return nil
}

// SetMultiAddresses removes all previously related items of the
// ip_address replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.IPAddresses's MultiAddresses accordingly.
// Replaces o.R.MultiAddresses with related.
// Sets related.R.IPAddresses's MultiAddresses accordingly.
func (o *IPAddress) SetMultiAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MultiAddress) error {
	query := "delete from \"multi_addresses_x_ip_addresses\" where \"ip_address_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeMultiAddressesFromIPAddressesSlice(o, related)
	if o.R != nil {
		o.R.MultiAddresses = nil
	}

	return o.AddMultiAddresses(ctx, exec, insert, related...)
}

// RemoveMultiAddresses relationships from objects passed in.
// Removes related items from R.MultiAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.IPAddresses.
func (o *IPAddress) RemoveMultiAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*MultiAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"multi_addresses_x_ip_addresses\" where \"ip_address_id\" = $1 and \"multi_address_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []any{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeMultiAddressesFromIPAddressesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.MultiAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.MultiAddresses)
			if ln > 1 && i < ln-1 {
				o.R.MultiAddresses[i] = o.R.MultiAddresses[ln-1]
			}
			o.R.MultiAddresses = o.R.MultiAddresses[:ln-1]
			break
		}
	}

	return nil
}

func removeMultiAddressesFromIPAddressesSlice(o *IPAddress, related []*MultiAddress) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.IPAddresses {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.IPAddresses)
			if ln > 1 && i < ln-1 {
				rel.R.IPAddresses[i] = rel.R.IPAddresses[ln-1]
			}
			rel.R.IPAddresses = rel.R.IPAddresses[:ln-1]
			break
		}
	}
}

// IPAddresses retrieves all the records using an executor.
func IPAddresses(mods ...qm.QueryMod) ipAddressQuery {
	mods = append(mods, qm.From("\"ip_addresses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ip_addresses\".*"})
	}

	return ipAddressQuery{q}
}

// FindIPAddress retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIPAddress(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*IPAddress, error) {
	ipAddressObj := &IPAddress{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ip_addresses\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, ipAddressObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from ip_addresses")
	}

	return ipAddressObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IPAddress) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no ip_addresses provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(ipAddressColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	ipAddressInsertCacheMut.RLock()
	cache, cached := ipAddressInsertCache[key]
	ipAddressInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			ipAddressAllColumns,
			ipAddressColumnsWithDefault,
			ipAddressColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, ipAddressGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(ipAddressType, ipAddressMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(ipAddressType, ipAddressMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ip_addresses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ip_addresses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into ip_addresses")
	}

	if !cached {
		ipAddressInsertCacheMut.Lock()
		ipAddressInsertCache[key] = cache
		ipAddressInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the IPAddress.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IPAddress) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	ipAddressUpdateCacheMut.RLock()
	cache, cached := ipAddressUpdateCache[key]
	ipAddressUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			ipAddressAllColumns,
			ipAddressPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, ipAddressGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update ip_addresses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ip_addresses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, ipAddressPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(ipAddressType, ipAddressMapping, append(wl, ipAddressPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update ip_addresses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for ip_addresses")
	}

	if !cached {
		ipAddressUpdateCacheMut.Lock()
		ipAddressUpdateCache[key] = cache
		ipAddressUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q ipAddressQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for ip_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for ip_addresses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IPAddressSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ipAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ip_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, ipAddressPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in ipAddress slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all ipAddress")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IPAddress) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no ip_addresses provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(ipAddressColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	ipAddressUpsertCacheMut.RLock()
	cache, cached := ipAddressUpsertCache[key]
	ipAddressUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			ipAddressAllColumns,
			ipAddressColumnsWithDefault,
			ipAddressColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			ipAddressAllColumns,
			ipAddressPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, ipAddressGeneratedColumns)
		update = strmangle.SetComplement(update, ipAddressGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert ip_addresses, could not build update column list")
		}

		ret := strmangle.SetComplement(ipAddressAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(ipAddressPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert ip_addresses, could not build conflict column list")
			}

			conflict = make([]string, len(ipAddressPrimaryKeyColumns))
			copy(conflict, ipAddressPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ip_addresses\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(ipAddressType, ipAddressMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(ipAddressType, ipAddressMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert ip_addresses")
	}

	if !cached {
		ipAddressUpsertCacheMut.Lock()
		ipAddressUpsertCache[key] = cache
		ipAddressUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single IPAddress record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IPAddress) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no IPAddress provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), ipAddressPrimaryKeyMapping)
	sql := "DELETE FROM \"ip_addresses\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from ip_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for ip_addresses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q ipAddressQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no ipAddressQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ip_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ip_addresses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IPAddressSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ipAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ip_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, ipAddressPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ipAddress slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ip_addresses")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IPAddress) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIPAddress(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IPAddressSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IPAddressSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ipAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ip_addresses\".* FROM \"ip_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, ipAddressPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in IPAddressSlice")
	}

	*o = slice

	return nil
}

// IPAddressExists checks if the IPAddress row exists.
func IPAddressExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ip_addresses\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if ip_addresses exists")
	}

	return exists, nil
}

// Exists checks if the IPAddress row exists.
func (o *IPAddress) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return IPAddressExists(ctx, exec, o.ID)
}
