// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PeersState is an object representing the database table.
type PeersState struct {
	// A unique id that identifies this peer.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// The peer id of the peer.
	PeerID int64 `boil:"peer_id" json:"peer_id" toml:"peer_id" yaml:"peer_id"`
	// The block height of the peer.
	BlockHeight null.Int64 `boil:"block_height" json:"block_height,omitempty" toml:"block_height" yaml:"block_height,omitempty"`
	// The JSON-RPC specification version of the peer.
	SpecVersion null.String `boil:"spec_version" json:"spec_version,omitempty" toml:"spec_version" yaml:"spec_version,omitempty"`
	// Whether the peer is synced when the record is made.
	IsSynced null.Bool `boil:"is_synced" json:"is_synced,omitempty" toml:"is_synced" yaml:"is_synced,omitempty"`
	// The time when the record was created.
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *peersStateR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L peersStateL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PeersStateColumns = struct {
	ID          string
	PeerID      string
	BlockHeight string
	SpecVersion string
	IsSynced    string
	CreatedAt   string
}{
	ID:          "id",
	PeerID:      "peer_id",
	BlockHeight: "block_height",
	SpecVersion: "spec_version",
	IsSynced:    "is_synced",
	CreatedAt:   "created_at",
}

var PeersStateTableColumns = struct {
	ID          string
	PeerID      string
	BlockHeight string
	SpecVersion string
	IsSynced    string
	CreatedAt   string
}{
	ID:          "peers_states.id",
	PeerID:      "peers_states.peer_id",
	BlockHeight: "peers_states.block_height",
	SpecVersion: "peers_states.spec_version",
	IsSynced:    "peers_states.is_synced",
	CreatedAt:   "peers_states.created_at",
}

// Generated where

var PeersStateWhere = struct {
	ID          whereHelperint
	PeerID      whereHelperint64
	BlockHeight whereHelpernull_Int64
	SpecVersion whereHelpernull_String
	IsSynced    whereHelpernull_Bool
	CreatedAt   whereHelpertime_Time
}{
	ID:          whereHelperint{field: "\"peers_states\".\"id\""},
	PeerID:      whereHelperint64{field: "\"peers_states\".\"peer_id\""},
	BlockHeight: whereHelpernull_Int64{field: "\"peers_states\".\"block_height\""},
	SpecVersion: whereHelpernull_String{field: "\"peers_states\".\"spec_version\""},
	IsSynced:    whereHelpernull_Bool{field: "\"peers_states\".\"is_synced\""},
	CreatedAt:   whereHelpertime_Time{field: "\"peers_states\".\"created_at\""},
}

// PeersStateRels is where relationship names are stored.
var PeersStateRels = struct {
	Peer string
}{
	Peer: "Peer",
}

// peersStateR is where relationships are stored.
type peersStateR struct {
	Peer *Peer `boil:"Peer" json:"Peer" toml:"Peer" yaml:"Peer"`
}

// NewStruct creates a new relationship struct
func (*peersStateR) NewStruct() *peersStateR {
	return &peersStateR{}
}

func (o *PeersState) GetPeer() *Peer {
	if o == nil {
		return nil
	}

	return o.R.GetPeer()
}

func (r *peersStateR) GetPeer() *Peer {
	if r == nil {
		return nil
	}

	return r.Peer
}

// peersStateL is where Load methods for each relationship are stored.
type peersStateL struct{}

var (
	peersStateAllColumns            = []string{"id", "peer_id", "block_height", "spec_version", "is_synced", "created_at"}
	peersStateColumnsWithoutDefault = []string{"peer_id", "created_at"}
	peersStateColumnsWithDefault    = []string{"id", "block_height", "spec_version", "is_synced"}
	peersStatePrimaryKeyColumns     = []string{"id"}
	peersStateGeneratedColumns      = []string{"id"}
)

type (
	// PeersStateSlice is an alias for a slice of pointers to PeersState.
	// This should almost always be used instead of []PeersState.
	PeersStateSlice []*PeersState

	peersStateQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	peersStateType                 = reflect.TypeOf(&PeersState{})
	peersStateMapping              = queries.MakeStructMapping(peersStateType)
	peersStatePrimaryKeyMapping, _ = queries.BindMapping(peersStateType, peersStateMapping, peersStatePrimaryKeyColumns)
	peersStateInsertCacheMut       sync.RWMutex
	peersStateInsertCache          = make(map[string]insertCache)
	peersStateUpdateCacheMut       sync.RWMutex
	peersStateUpdateCache          = make(map[string]updateCache)
	peersStateUpsertCacheMut       sync.RWMutex
	peersStateUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single peersState record from the query.
func (q peersStateQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PeersState, error) {
	o := &PeersState{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for peers_states")
	}

	return o, nil
}

// All returns all PeersState records from the query.
func (q peersStateQuery) All(ctx context.Context, exec boil.ContextExecutor) (PeersStateSlice, error) {
	var o []*PeersState

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PeersState slice")
	}

	return o, nil
}

// Count returns the count of all PeersState records in the query.
func (q peersStateQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count peers_states rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q peersStateQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if peers_states exists")
	}

	return count > 0, nil
}

// Peer pointed to by the foreign key.
func (o *PeersState) Peer(mods ...qm.QueryMod) peerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PeerID),
	}

	queryMods = append(queryMods, mods...)

	return Peers(queryMods...)
}

// LoadPeer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (peersStateL) LoadPeer(ctx context.Context, e boil.ContextExecutor, singular bool, maybePeersState any, mods queries.Applicator) error {
	var slice []*PeersState
	var object *PeersState

	if singular {
		var ok bool
		object, ok = maybePeersState.(*PeersState)
		if !ok {
			object = new(PeersState)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePeersState)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePeersState))
			}
		}
	} else {
		s, ok := maybePeersState.(*[]*PeersState)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePeersState)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePeersState))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &peersStateR{}
		}
		args[object.PeerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &peersStateR{}
			}

			args[obj.PeerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`peers`),
		qm.WhereIn(`peers.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Peer")
	}

	var resultSlice []*Peer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Peer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for peers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for peers")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Peer = foreign
		if foreign.R == nil {
			foreign.R = &peerR{}
		}
		foreign.R.PeersStates = append(foreign.R.PeersStates, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PeerID == foreign.ID {
				local.R.Peer = foreign
				if foreign.R == nil {
					foreign.R = &peerR{}
				}
				foreign.R.PeersStates = append(foreign.R.PeersStates, local)
				break
			}
		}
	}

	return nil
}

// SetPeer of the peersState to the related item.
// Sets o.R.Peer to related.
// Adds o to related.R.PeersStates.
func (o *PeersState) SetPeer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Peer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"peers_states\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"peer_id"}),
		strmangle.WhereClause("\"", "\"", 2, peersStatePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PeerID = related.ID
	if o.R == nil {
		o.R = &peersStateR{
			Peer: related,
		}
	} else {
		o.R.Peer = related
	}

	if related.R == nil {
		related.R = &peerR{
			PeersStates: PeersStateSlice{o},
		}
	} else {
		related.R.PeersStates = append(related.R.PeersStates, o)
	}

	return nil
}

// PeersStates retrieves all the records using an executor.
func PeersStates(mods ...qm.QueryMod) peersStateQuery {
	mods = append(mods, qm.From("\"peers_states\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"peers_states\".*"})
	}

	return peersStateQuery{q}
}

// FindPeersState retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPeersState(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*PeersState, error) {
	peersStateObj := &PeersState{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"peers_states\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, peersStateObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from peers_states")
	}

	return peersStateObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PeersState) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no peers_states provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(peersStateColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	peersStateInsertCacheMut.RLock()
	cache, cached := peersStateInsertCache[key]
	peersStateInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			peersStateAllColumns,
			peersStateColumnsWithDefault,
			peersStateColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, peersStateGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(peersStateType, peersStateMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(peersStateType, peersStateMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"peers_states\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"peers_states\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into peers_states")
	}

	if !cached {
		peersStateInsertCacheMut.Lock()
		peersStateInsertCache[key] = cache
		peersStateInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the PeersState.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PeersState) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	peersStateUpdateCacheMut.RLock()
	cache, cached := peersStateUpdateCache[key]
	peersStateUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			peersStateAllColumns,
			peersStatePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, peersStateGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update peers_states, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"peers_states\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, peersStatePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(peersStateType, peersStateMapping, append(wl, peersStatePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update peers_states row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for peers_states")
	}

	if !cached {
		peersStateUpdateCacheMut.Lock()
		peersStateUpdateCache[key] = cache
		peersStateUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q peersStateQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for peers_states")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for peers_states")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PeersStateSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), peersStatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"peers_states\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, peersStatePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in peersState slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all peersState")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PeersState) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no peers_states provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(peersStateColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	peersStateUpsertCacheMut.RLock()
	cache, cached := peersStateUpsertCache[key]
	peersStateUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			peersStateAllColumns,
			peersStateColumnsWithDefault,
			peersStateColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			peersStateAllColumns,
			peersStatePrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, peersStateGeneratedColumns)
		update = strmangle.SetComplement(update, peersStateGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert peers_states, could not build update column list")
		}

		ret := strmangle.SetComplement(peersStateAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(peersStatePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert peers_states, could not build conflict column list")
			}

			conflict = make([]string, len(peersStatePrimaryKeyColumns))
			copy(conflict, peersStatePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"peers_states\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(peersStateType, peersStateMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(peersStateType, peersStateMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert peers_states")
	}

	if !cached {
		peersStateUpsertCacheMut.Lock()
		peersStateUpsertCache[key] = cache
		peersStateUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single PeersState record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PeersState) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PeersState provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), peersStatePrimaryKeyMapping)
	sql := "DELETE FROM \"peers_states\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from peers_states")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for peers_states")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q peersStateQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no peersStateQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from peers_states")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for peers_states")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PeersStateSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), peersStatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"peers_states\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, peersStatePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from peersState slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for peers_states")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PeersState) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPeersState(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PeersStateSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PeersStateSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), peersStatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"peers_states\".* FROM \"peers_states\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, peersStatePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PeersStateSlice")
	}

	*o = slice

	return nil
}

// PeersStateExists checks if the PeersState row exists.
func PeersStateExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"peers_states\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if peers_states exists")
	}

	return exists, nil
}

// Exists checks if the PeersState row exists.
func (o *PeersState) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PeersStateExists(ctx, exec, o.ID)
}
