// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Protocol is an object representing the database table.
type Protocol struct {
	// A unique id that identifies a agent version.
	ID int `boil:"id" json:"id" toml:"id" yaml:"id"`
	// Timestamp of when this protocol was seen the last time.
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// The full protocol string.
	Protocol string `boil:"protocol" json:"protocol" toml:"protocol" yaml:"protocol"`
	// The count of the protocol.
	Count int `boil:"count" json:"count" toml:"count" yaml:"count"`
	// Timestamp of when this protocol was updated.
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *protocolR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L protocolL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProtocolColumns = struct {
	ID        string
	CreatedAt string
	Protocol  string
	Count     string
	UpdatedAt string
}{
	ID:        "id",
	CreatedAt: "created_at",
	Protocol:  "protocol",
	Count:     "count",
	UpdatedAt: "updated_at",
}

var ProtocolTableColumns = struct {
	ID        string
	CreatedAt string
	Protocol  string
	Count     string
	UpdatedAt string
}{
	ID:        "protocols.id",
	CreatedAt: "protocols.created_at",
	Protocol:  "protocols.protocol",
	Count:     "protocols.count",
	UpdatedAt: "protocols.updated_at",
}

// Generated where

var ProtocolWhere = struct {
	ID        whereHelperint
	CreatedAt whereHelpertime_Time
	Protocol  whereHelperstring
	Count     whereHelperint
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "\"protocols\".\"id\""},
	CreatedAt: whereHelpertime_Time{field: "\"protocols\".\"created_at\""},
	Protocol:  whereHelperstring{field: "\"protocols\".\"protocol\""},
	Count:     whereHelperint{field: "\"protocols\".\"count\""},
	UpdatedAt: whereHelpertime_Time{field: "\"protocols\".\"updated_at\""},
}

// ProtocolRels is where relationship names are stored.
var ProtocolRels = struct {
}{}

// protocolR is where relationships are stored.
type protocolR struct {
}

// NewStruct creates a new relationship struct
func (*protocolR) NewStruct() *protocolR {
	return &protocolR{}
}

// protocolL is where Load methods for each relationship are stored.
type protocolL struct{}

var (
	protocolAllColumns            = []string{"id", "created_at", "protocol", "count", "updated_at"}
	protocolColumnsWithoutDefault = []string{"created_at", "protocol", "count", "updated_at"}
	protocolColumnsWithDefault    = []string{"id"}
	protocolPrimaryKeyColumns     = []string{"id"}
	protocolGeneratedColumns      = []string{"id"}
)

type (
	// ProtocolSlice is an alias for a slice of pointers to Protocol.
	// This should almost always be used instead of []Protocol.
	ProtocolSlice []*Protocol

	protocolQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	protocolType                 = reflect.TypeOf(&Protocol{})
	protocolMapping              = queries.MakeStructMapping(protocolType)
	protocolPrimaryKeyMapping, _ = queries.BindMapping(protocolType, protocolMapping, protocolPrimaryKeyColumns)
	protocolInsertCacheMut       sync.RWMutex
	protocolInsertCache          = make(map[string]insertCache)
	protocolUpdateCacheMut       sync.RWMutex
	protocolUpdateCache          = make(map[string]updateCache)
	protocolUpsertCacheMut       sync.RWMutex
	protocolUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single protocol record from the query.
func (q protocolQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Protocol, error) {
	o := &Protocol{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for protocols")
	}

	return o, nil
}

// All returns all Protocol records from the query.
func (q protocolQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProtocolSlice, error) {
	var o []*Protocol

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Protocol slice")
	}

	return o, nil
}

// Count returns the count of all Protocol records in the query.
func (q protocolQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count protocols rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q protocolQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if protocols exists")
	}

	return count > 0, nil
}

// Protocols retrieves all the records using an executor.
func Protocols(mods ...qm.QueryMod) protocolQuery {
	mods = append(mods, qm.From("\"protocols\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"protocols\".*"})
	}

	return protocolQuery{q}
}

// FindProtocol retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProtocol(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Protocol, error) {
	protocolObj := &Protocol{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"protocols\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, protocolObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from protocols")
	}

	return protocolObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Protocol) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no protocols provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(protocolColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	protocolInsertCacheMut.RLock()
	cache, cached := protocolInsertCache[key]
	protocolInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			protocolAllColumns,
			protocolColumnsWithDefault,
			protocolColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, protocolGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(protocolType, protocolMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(protocolType, protocolMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"protocols\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"protocols\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into protocols")
	}

	if !cached {
		protocolInsertCacheMut.Lock()
		protocolInsertCache[key] = cache
		protocolInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Protocol.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Protocol) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	protocolUpdateCacheMut.RLock()
	cache, cached := protocolUpdateCache[key]
	protocolUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			protocolAllColumns,
			protocolPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, protocolGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update protocols, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"protocols\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, protocolPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(protocolType, protocolMapping, append(wl, protocolPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update protocols row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for protocols")
	}

	if !cached {
		protocolUpdateCacheMut.Lock()
		protocolUpdateCache[key] = cache
		protocolUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q protocolQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for protocols")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for protocols")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProtocolSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), protocolPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"protocols\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, protocolPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in protocol slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all protocol")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Protocol) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no protocols provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(protocolColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	protocolUpsertCacheMut.RLock()
	cache, cached := protocolUpsertCache[key]
	protocolUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			protocolAllColumns,
			protocolColumnsWithDefault,
			protocolColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			protocolAllColumns,
			protocolPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, protocolGeneratedColumns)
		update = strmangle.SetComplement(update, protocolGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert protocols, could not build update column list")
		}

		ret := strmangle.SetComplement(protocolAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(protocolPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert protocols, could not build conflict column list")
			}

			conflict = make([]string, len(protocolPrimaryKeyColumns))
			copy(conflict, protocolPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"protocols\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(protocolType, protocolMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(protocolType, protocolMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert protocols")
	}

	if !cached {
		protocolUpsertCacheMut.Lock()
		protocolUpsertCache[key] = cache
		protocolUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Protocol record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Protocol) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Protocol provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), protocolPrimaryKeyMapping)
	sql := "DELETE FROM \"protocols\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from protocols")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for protocols")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q protocolQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no protocolQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from protocols")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for protocols")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProtocolSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), protocolPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"protocols\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, protocolPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from protocol slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for protocols")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Protocol) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProtocol(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProtocolSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProtocolSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), protocolPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"protocols\".* FROM \"protocols\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, protocolPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProtocolSlice")
	}

	*o = slice

	return nil
}

// ProtocolExists checks if the Protocol row exists.
func ProtocolExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"protocols\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if protocols exists")
	}

	return exists, nil
}

// Exists checks if the Protocol row exists.
func (o *Protocol) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProtocolExists(ctx, exec, o.ID)
}
