// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Visit is an object representing the database table.
type Visit struct {
	// A unique id that identifies this visit.
	ID int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	// Which peer did we meet.
	PeerID int64 `boil:"peer_id" json:"peer_id" toml:"peer_id" yaml:"peer_id"`
	// The agent version that this peer reported during this visit.
	AgentVersionID null.Int `boil:"agent_version_id" json:"agent_version_id,omitempty" toml:"agent_version_id" yaml:"agent_version_id,omitempty"`
	// The set of supported protocols that this peer reported.
	ProtocolsSetID null.Int `boil:"protocols_set_id" json:"protocols_set_id,omitempty" toml:"protocols_set_id" yaml:"protocols_set_id,omitempty"`
	// The error that happened for this visit.
	ConnectError null.String `boil:"connect_error" json:"connect_error,omitempty" toml:"connect_error" yaml:"connect_error,omitempty"`
	// The error that happened when crawling the peer.
	CrawlError null.String `boil:"crawl_error" json:"crawl_error,omitempty" toml:"crawl_error" yaml:"crawl_error,omitempty"`
	// The time it took to connect with the peer.
	VisitStartedAt time.Time `boil:"visit_started_at" json:"visit_started_at" toml:"visit_started_at" yaml:"visit_started_at"`
	// The time it took to connect with the peer.
	VisitEndedAt time.Time `boil:"visit_ended_at" json:"visit_ended_at" toml:"visit_ended_at" yaml:"visit_ended_at"`
	// The time it took to connect with the peer or until an error occurred.
	ConnectDuration null.String `boil:"connect_duration" json:"connect_duration,omitempty" toml:"connect_duration" yaml:"connect_duration,omitempty"`
	// The time it took to crawl the peer also if an error occurred.
	CrawlDuration null.String `boil:"crawl_duration" json:"crawl_duration,omitempty" toml:"crawl_duration" yaml:"crawl_duration,omitempty"`
	// An array of all multi address IDs of the remote peer.
	MultiAddressIds types.Int64Array `boil:"multi_address_ids" json:"multi_address_ids,omitempty" toml:"multi_address_ids" yaml:"multi_address_ids,omitempty"`
	CrawlID         null.Int         `boil:"crawl_id" json:"crawl_id,omitempty" toml:"crawl_id" yaml:"crawl_id,omitempty"`

	R *visitR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L visitL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VisitColumns = struct {
	ID              string
	PeerID          string
	AgentVersionID  string
	ProtocolsSetID  string
	ConnectError    string
	CrawlError      string
	VisitStartedAt  string
	VisitEndedAt    string
	ConnectDuration string
	CrawlDuration   string
	MultiAddressIds string
	CrawlID         string
}{
	ID:              "id",
	PeerID:          "peer_id",
	AgentVersionID:  "agent_version_id",
	ProtocolsSetID:  "protocols_set_id",
	ConnectError:    "connect_error",
	CrawlError:      "crawl_error",
	VisitStartedAt:  "visit_started_at",
	VisitEndedAt:    "visit_ended_at",
	ConnectDuration: "connect_duration",
	CrawlDuration:   "crawl_duration",
	MultiAddressIds: "multi_address_ids",
	CrawlID:         "crawl_id",
}

var VisitTableColumns = struct {
	ID              string
	PeerID          string
	AgentVersionID  string
	ProtocolsSetID  string
	ConnectError    string
	CrawlError      string
	VisitStartedAt  string
	VisitEndedAt    string
	ConnectDuration string
	CrawlDuration   string
	MultiAddressIds string
	CrawlID         string
}{
	ID:              "visits.id",
	PeerID:          "visits.peer_id",
	AgentVersionID:  "visits.agent_version_id",
	ProtocolsSetID:  "visits.protocols_set_id",
	ConnectError:    "visits.connect_error",
	CrawlError:      "visits.crawl_error",
	VisitStartedAt:  "visits.visit_started_at",
	VisitEndedAt:    "visits.visit_ended_at",
	ConnectDuration: "visits.connect_duration",
	CrawlDuration:   "visits.crawl_duration",
	MultiAddressIds: "visits.multi_address_ids",
	CrawlID:         "visits.crawl_id",
}

// Generated where

var VisitWhere = struct {
	ID              whereHelperint64
	PeerID          whereHelperint64
	AgentVersionID  whereHelpernull_Int
	ProtocolsSetID  whereHelpernull_Int
	ConnectError    whereHelpernull_String
	CrawlError      whereHelpernull_String
	VisitStartedAt  whereHelpertime_Time
	VisitEndedAt    whereHelpertime_Time
	ConnectDuration whereHelpernull_String
	CrawlDuration   whereHelpernull_String
	MultiAddressIds whereHelpertypes_Int64Array
	CrawlID         whereHelpernull_Int
}{
	ID:              whereHelperint64{field: "\"visits\".\"id\""},
	PeerID:          whereHelperint64{field: "\"visits\".\"peer_id\""},
	AgentVersionID:  whereHelpernull_Int{field: "\"visits\".\"agent_version_id\""},
	ProtocolsSetID:  whereHelpernull_Int{field: "\"visits\".\"protocols_set_id\""},
	ConnectError:    whereHelpernull_String{field: "\"visits\".\"connect_error\""},
	CrawlError:      whereHelpernull_String{field: "\"visits\".\"crawl_error\""},
	VisitStartedAt:  whereHelpertime_Time{field: "\"visits\".\"visit_started_at\""},
	VisitEndedAt:    whereHelpertime_Time{field: "\"visits\".\"visit_ended_at\""},
	ConnectDuration: whereHelpernull_String{field: "\"visits\".\"connect_duration\""},
	CrawlDuration:   whereHelpernull_String{field: "\"visits\".\"crawl_duration\""},
	MultiAddressIds: whereHelpertypes_Int64Array{field: "\"visits\".\"multi_address_ids\""},
	CrawlID:         whereHelpernull_Int{field: "\"visits\".\"crawl_id\""},
}

// VisitRels is where relationship names are stored.
var VisitRels = struct {
	AgentVersion string
	Crawl        string
	Peer         string
	ProtocolsSet string
}{
	AgentVersion: "AgentVersion",
	Crawl:        "Crawl",
	Peer:         "Peer",
	ProtocolsSet: "ProtocolsSet",
}

// visitR is where relationships are stored.
type visitR struct {
	AgentVersion *AgentVersion `boil:"AgentVersion" json:"AgentVersion" toml:"AgentVersion" yaml:"AgentVersion"`
	Crawl        *Crawl        `boil:"Crawl" json:"Crawl" toml:"Crawl" yaml:"Crawl"`
	Peer         *Peer         `boil:"Peer" json:"Peer" toml:"Peer" yaml:"Peer"`
	ProtocolsSet *ProtocolsSet `boil:"ProtocolsSet" json:"ProtocolsSet" toml:"ProtocolsSet" yaml:"ProtocolsSet"`
}

// NewStruct creates a new relationship struct
func (*visitR) NewStruct() *visitR {
	return &visitR{}
}

func (o *Visit) GetAgentVersion() *AgentVersion {
	if o == nil {
		return nil
	}

	return o.R.GetAgentVersion()
}

func (r *visitR) GetAgentVersion() *AgentVersion {
	if r == nil {
		return nil
	}

	return r.AgentVersion
}

func (o *Visit) GetCrawl() *Crawl {
	if o == nil {
		return nil
	}

	return o.R.GetCrawl()
}

func (r *visitR) GetCrawl() *Crawl {
	if r == nil {
		return nil
	}

	return r.Crawl
}

func (o *Visit) GetPeer() *Peer {
	if o == nil {
		return nil
	}

	return o.R.GetPeer()
}

func (r *visitR) GetPeer() *Peer {
	if r == nil {
		return nil
	}

	return r.Peer
}

func (o *Visit) GetProtocolsSet() *ProtocolsSet {
	if o == nil {
		return nil
	}

	return o.R.GetProtocolsSet()
}

func (r *visitR) GetProtocolsSet() *ProtocolsSet {
	if r == nil {
		return nil
	}

	return r.ProtocolsSet
}

// visitL is where Load methods for each relationship are stored.
type visitL struct{}

var (
	visitAllColumns            = []string{"id", "peer_id", "agent_version_id", "protocols_set_id", "connect_error", "crawl_error", "visit_started_at", "visit_ended_at", "connect_duration", "crawl_duration", "multi_address_ids", "crawl_id"}
	visitColumnsWithoutDefault = []string{"peer_id", "visit_started_at", "visit_ended_at"}
	visitColumnsWithDefault    = []string{"id", "agent_version_id", "protocols_set_id", "connect_error", "crawl_error", "connect_duration", "crawl_duration", "multi_address_ids", "crawl_id"}
	visitPrimaryKeyColumns     = []string{"id", "visit_started_at"}
	visitGeneratedColumns      = []string{"id"}
)

type (
	// VisitSlice is an alias for a slice of pointers to Visit.
	// This should almost always be used instead of []Visit.
	VisitSlice []*Visit

	visitQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	visitType                 = reflect.TypeOf(&Visit{})
	visitMapping              = queries.MakeStructMapping(visitType)
	visitPrimaryKeyMapping, _ = queries.BindMapping(visitType, visitMapping, visitPrimaryKeyColumns)
	visitInsertCacheMut       sync.RWMutex
	visitInsertCache          = make(map[string]insertCache)
	visitUpdateCacheMut       sync.RWMutex
	visitUpdateCache          = make(map[string]updateCache)
	visitUpsertCacheMut       sync.RWMutex
	visitUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single visit record from the query.
func (q visitQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Visit, error) {
	o := &Visit{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for visits")
	}

	return o, nil
}

// All returns all Visit records from the query.
func (q visitQuery) All(ctx context.Context, exec boil.ContextExecutor) (VisitSlice, error) {
	var o []*Visit

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Visit slice")
	}

	return o, nil
}

// Count returns the count of all Visit records in the query.
func (q visitQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count visits rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q visitQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if visits exists")
	}

	return count > 0, nil
}

// AgentVersion pointed to by the foreign key.
func (o *Visit) AgentVersion(mods ...qm.QueryMod) agentVersionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AgentVersionID),
	}

	queryMods = append(queryMods, mods...)

	return AgentVersions(queryMods...)
}

// Crawl pointed to by the foreign key.
func (o *Visit) Crawl(mods ...qm.QueryMod) crawlQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CrawlID),
	}

	queryMods = append(queryMods, mods...)

	return Crawls(queryMods...)
}

// Peer pointed to by the foreign key.
func (o *Visit) Peer(mods ...qm.QueryMod) peerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PeerID),
	}

	queryMods = append(queryMods, mods...)

	return Peers(queryMods...)
}

// ProtocolsSet pointed to by the foreign key.
func (o *Visit) ProtocolsSet(mods ...qm.QueryMod) protocolsSetQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProtocolsSetID),
	}

	queryMods = append(queryMods, mods...)

	return ProtocolsSets(queryMods...)
}

// LoadAgentVersion allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (visitL) LoadAgentVersion(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVisit any, mods queries.Applicator) error {
	var slice []*Visit
	var object *Visit

	if singular {
		var ok bool
		object, ok = maybeVisit.(*Visit)
		if !ok {
			object = new(Visit)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVisit))
			}
		}
	} else {
		s, ok := maybeVisit.(*[]*Visit)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVisit))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &visitR{}
		}
		if !queries.IsNil(object.AgentVersionID) {
			args[object.AgentVersionID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &visitR{}
			}

			if !queries.IsNil(obj.AgentVersionID) {
				args[obj.AgentVersionID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`agent_versions`),
		qm.WhereIn(`agent_versions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AgentVersion")
	}

	var resultSlice []*AgentVersion
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AgentVersion")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for agent_versions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for agent_versions")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.AgentVersion = foreign
		if foreign.R == nil {
			foreign.R = &agentVersionR{}
		}
		foreign.R.Visits = append(foreign.R.Visits, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AgentVersionID, foreign.ID) {
				local.R.AgentVersion = foreign
				if foreign.R == nil {
					foreign.R = &agentVersionR{}
				}
				foreign.R.Visits = append(foreign.R.Visits, local)
				break
			}
		}
	}

	return nil
}

// LoadCrawl allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (visitL) LoadCrawl(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVisit any, mods queries.Applicator) error {
	var slice []*Visit
	var object *Visit

	if singular {
		var ok bool
		object, ok = maybeVisit.(*Visit)
		if !ok {
			object = new(Visit)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVisit))
			}
		}
	} else {
		s, ok := maybeVisit.(*[]*Visit)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVisit))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &visitR{}
		}
		if !queries.IsNil(object.CrawlID) {
			args[object.CrawlID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &visitR{}
			}

			if !queries.IsNil(obj.CrawlID) {
				args[obj.CrawlID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`crawls`),
		qm.WhereIn(`crawls.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Crawl")
	}

	var resultSlice []*Crawl
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Crawl")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for crawls")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for crawls")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Crawl = foreign
		if foreign.R == nil {
			foreign.R = &crawlR{}
		}
		foreign.R.Visits = append(foreign.R.Visits, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CrawlID, foreign.ID) {
				local.R.Crawl = foreign
				if foreign.R == nil {
					foreign.R = &crawlR{}
				}
				foreign.R.Visits = append(foreign.R.Visits, local)
				break
			}
		}
	}

	return nil
}

// LoadPeer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (visitL) LoadPeer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVisit any, mods queries.Applicator) error {
	var slice []*Visit
	var object *Visit

	if singular {
		var ok bool
		object, ok = maybeVisit.(*Visit)
		if !ok {
			object = new(Visit)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVisit))
			}
		}
	} else {
		s, ok := maybeVisit.(*[]*Visit)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVisit))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &visitR{}
		}
		args[object.PeerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &visitR{}
			}

			args[obj.PeerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`peers`),
		qm.WhereIn(`peers.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Peer")
	}

	var resultSlice []*Peer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Peer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for peers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for peers")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Peer = foreign
		if foreign.R == nil {
			foreign.R = &peerR{}
		}
		foreign.R.Visits = append(foreign.R.Visits, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PeerID == foreign.ID {
				local.R.Peer = foreign
				if foreign.R == nil {
					foreign.R = &peerR{}
				}
				foreign.R.Visits = append(foreign.R.Visits, local)
				break
			}
		}
	}

	return nil
}

// LoadProtocolsSet allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (visitL) LoadProtocolsSet(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVisit any, mods queries.Applicator) error {
	var slice []*Visit
	var object *Visit

	if singular {
		var ok bool
		object, ok = maybeVisit.(*Visit)
		if !ok {
			object = new(Visit)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVisit))
			}
		}
	} else {
		s, ok := maybeVisit.(*[]*Visit)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVisit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVisit))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &visitR{}
		}
		if !queries.IsNil(object.ProtocolsSetID) {
			args[object.ProtocolsSetID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &visitR{}
			}

			if !queries.IsNil(obj.ProtocolsSetID) {
				args[obj.ProtocolsSetID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`protocols_sets`),
		qm.WhereIn(`protocols_sets.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ProtocolsSet")
	}

	var resultSlice []*ProtocolsSet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ProtocolsSet")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for protocols_sets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for protocols_sets")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ProtocolsSet = foreign
		if foreign.R == nil {
			foreign.R = &protocolsSetR{}
		}
		foreign.R.Visits = append(foreign.R.Visits, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ProtocolsSetID, foreign.ID) {
				local.R.ProtocolsSet = foreign
				if foreign.R == nil {
					foreign.R = &protocolsSetR{}
				}
				foreign.R.Visits = append(foreign.R.Visits, local)
				break
			}
		}
	}

	return nil
}

// SetAgentVersion of the visit to the related item.
// Sets o.R.AgentVersion to related.
// Adds o to related.R.Visits.
func (o *Visit) SetAgentVersion(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AgentVersion) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"visits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"agent_version_id"}),
		strmangle.WhereClause("\"", "\"", 2, visitPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID, o.VisitStartedAt}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AgentVersionID, related.ID)
	if o.R == nil {
		o.R = &visitR{
			AgentVersion: related,
		}
	} else {
		o.R.AgentVersion = related
	}

	if related.R == nil {
		related.R = &agentVersionR{
			Visits: VisitSlice{o},
		}
	} else {
		related.R.Visits = append(related.R.Visits, o)
	}

	return nil
}

// RemoveAgentVersion relationship.
// Sets o.R.AgentVersion to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Visit) RemoveAgentVersion(ctx context.Context, exec boil.ContextExecutor, related *AgentVersion) error {
	var err error

	queries.SetScanner(&o.AgentVersionID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("agent_version_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.AgentVersion = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Visits {
		if queries.Equal(o.AgentVersionID, ri.AgentVersionID) {
			continue
		}

		ln := len(related.R.Visits)
		if ln > 1 && i < ln-1 {
			related.R.Visits[i] = related.R.Visits[ln-1]
		}
		related.R.Visits = related.R.Visits[:ln-1]
		break
	}
	return nil
}

// SetCrawl of the visit to the related item.
// Sets o.R.Crawl to related.
// Adds o to related.R.Visits.
func (o *Visit) SetCrawl(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Crawl) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"visits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"crawl_id"}),
		strmangle.WhereClause("\"", "\"", 2, visitPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID, o.VisitStartedAt}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CrawlID, related.ID)
	if o.R == nil {
		o.R = &visitR{
			Crawl: related,
		}
	} else {
		o.R.Crawl = related
	}

	if related.R == nil {
		related.R = &crawlR{
			Visits: VisitSlice{o},
		}
	} else {
		related.R.Visits = append(related.R.Visits, o)
	}

	return nil
}

// RemoveCrawl relationship.
// Sets o.R.Crawl to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Visit) RemoveCrawl(ctx context.Context, exec boil.ContextExecutor, related *Crawl) error {
	var err error

	queries.SetScanner(&o.CrawlID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("crawl_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Crawl = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Visits {
		if queries.Equal(o.CrawlID, ri.CrawlID) {
			continue
		}

		ln := len(related.R.Visits)
		if ln > 1 && i < ln-1 {
			related.R.Visits[i] = related.R.Visits[ln-1]
		}
		related.R.Visits = related.R.Visits[:ln-1]
		break
	}
	return nil
}

// SetPeer of the visit to the related item.
// Sets o.R.Peer to related.
// Adds o to related.R.Visits.
func (o *Visit) SetPeer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Peer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"visits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"peer_id"}),
		strmangle.WhereClause("\"", "\"", 2, visitPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID, o.VisitStartedAt}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PeerID = related.ID
	if o.R == nil {
		o.R = &visitR{
			Peer: related,
		}
	} else {
		o.R.Peer = related
	}

	if related.R == nil {
		related.R = &peerR{
			Visits: VisitSlice{o},
		}
	} else {
		related.R.Visits = append(related.R.Visits, o)
	}

	return nil
}

// SetProtocolsSet of the visit to the related item.
// Sets o.R.ProtocolsSet to related.
// Adds o to related.R.Visits.
func (o *Visit) SetProtocolsSet(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ProtocolsSet) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"visits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"protocols_set_id"}),
		strmangle.WhereClause("\"", "\"", 2, visitPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID, o.VisitStartedAt}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ProtocolsSetID, related.ID)
	if o.R == nil {
		o.R = &visitR{
			ProtocolsSet: related,
		}
	} else {
		o.R.ProtocolsSet = related
	}

	if related.R == nil {
		related.R = &protocolsSetR{
			Visits: VisitSlice{o},
		}
	} else {
		related.R.Visits = append(related.R.Visits, o)
	}

	return nil
}

// RemoveProtocolsSet relationship.
// Sets o.R.ProtocolsSet to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Visit) RemoveProtocolsSet(ctx context.Context, exec boil.ContextExecutor, related *ProtocolsSet) error {
	var err error

	queries.SetScanner(&o.ProtocolsSetID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("protocols_set_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ProtocolsSet = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Visits {
		if queries.Equal(o.ProtocolsSetID, ri.ProtocolsSetID) {
			continue
		}

		ln := len(related.R.Visits)
		if ln > 1 && i < ln-1 {
			related.R.Visits[i] = related.R.Visits[ln-1]
		}
		related.R.Visits = related.R.Visits[:ln-1]
		break
	}
	return nil
}

// Visits retrieves all the records using an executor.
func Visits(mods ...qm.QueryMod) visitQuery {
	mods = append(mods, qm.From("\"visits\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"visits\".*"})
	}

	return visitQuery{q}
}

// FindVisit retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVisit(ctx context.Context, exec boil.ContextExecutor, iD int64, visitStartedAt time.Time, selectCols ...string) (*Visit, error) {
	visitObj := &Visit{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"visits\" where \"id\"=$1 AND \"visit_started_at\"=$2", sel,
	)

	q := queries.Raw(query, iD, visitStartedAt)

	err := q.Bind(ctx, exec, visitObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from visits")
	}

	return visitObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Visit) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no visits provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(visitColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	visitInsertCacheMut.RLock()
	cache, cached := visitInsertCache[key]
	visitInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			visitAllColumns,
			visitColumnsWithDefault,
			visitColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, visitGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(visitType, visitMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(visitType, visitMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"visits\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"visits\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into visits")
	}

	if !cached {
		visitInsertCacheMut.Lock()
		visitInsertCache[key] = cache
		visitInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Visit.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Visit) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	visitUpdateCacheMut.RLock()
	cache, cached := visitUpdateCache[key]
	visitUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			visitAllColumns,
			visitPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, visitGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update visits, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"visits\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, visitPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(visitType, visitMapping, append(wl, visitPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update visits row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for visits")
	}

	if !cached {
		visitUpdateCacheMut.Lock()
		visitUpdateCache[key] = cache
		visitUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q visitQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for visits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for visits")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VisitSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), visitPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"visits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, visitPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in visit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all visit")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Visit) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no visits provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(visitColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	visitUpsertCacheMut.RLock()
	cache, cached := visitUpsertCache[key]
	visitUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			visitAllColumns,
			visitColumnsWithDefault,
			visitColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			visitAllColumns,
			visitPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, visitGeneratedColumns)
		update = strmangle.SetComplement(update, visitGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert visits, could not build update column list")
		}

		ret := strmangle.SetComplement(visitAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(visitPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert visits, could not build conflict column list")
			}

			conflict = make([]string, len(visitPrimaryKeyColumns))
			copy(conflict, visitPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"visits\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(visitType, visitMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(visitType, visitMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert visits")
	}

	if !cached {
		visitUpsertCacheMut.Lock()
		visitUpsertCache[key] = cache
		visitUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Visit record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Visit) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Visit provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), visitPrimaryKeyMapping)
	sql := "DELETE FROM \"visits\" WHERE \"id\"=$1 AND \"visit_started_at\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from visits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for visits")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q visitQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no visitQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from visits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for visits")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VisitSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), visitPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"visits\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, visitPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from visit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for visits")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Visit) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVisit(ctx, exec, o.ID, o.VisitStartedAt)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VisitSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VisitSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), visitPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"visits\".* FROM \"visits\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, visitPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VisitSlice")
	}

	*o = slice

	return nil
}

// VisitExists checks if the Visit row exists.
func VisitExists(ctx context.Context, exec boil.ContextExecutor, iD int64, visitStartedAt time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"visits\" where \"id\"=$1 AND \"visit_started_at\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD, visitStartedAt)
	}
	row := exec.QueryRowContext(ctx, sql, iD, visitStartedAt)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if visits exists")
	}

	return exists, nil
}

// Exists checks if the Visit row exists.
func (o *Visit) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VisitExists(ctx, exec, o.ID, o.VisitStartedAt)
}
